/* class,name,weight,objclass,dir,canpickup,simulation,fnc,icon */
Config_Items = [
    /* Foods */
    ["donut","Rosquinha",1,"",0,true,true,"Caue_Items_Eat",""],
    ["cereal","Cereal",1,"Land_CerealsBox_F",90,true,true,"Caue_Items_Eat",""],
    ["lamington","Bolo de Carne",0.1,"A3PL_Lamington",0,true,true,"Caue_Items_Eat",""],
    ["sausages","Salsichas",0.1,"A3PL_Sausages",0,true,true,"Caue_Items_Eat",""],
    ["meatpie","Torta de carne",0.1,"A3PL_MeatPie",0,true,true,"Caue_Items_Eat",""],
    ["burger_bun","Pão de hamburguer",0.5,"A3PL_Burger_Bun",0,true,true,"Caue_Items_Eat",""],
    ["burger_burnt","Hamburger de peixe queimado",0.5,"A3PL_Burger_Burnt",0,true,true,"Caue_Items_Eat",""],
    ["burger_raw","Hamburger de peixe (mcdonalds)",0.5,"A3PL_Burger_Raw",90,true,true,"Caue_Items_Eat",""],
    ["burger_cooked","Hamburger de peixe frito",0.5,"A3PL_Burger_Cooked",0,true,true,"Caue_Items_Eat",""],
    ["burger_full_raw","Hambúrguer De Peixe Cru",1,"A3PL_Burger_Full",0,true,true,"Caue_Items_Eat",""],
    ["burger_full_cooked","Hambúrguer de peixe cozido",1,"A3PL_Burger_Full",0,true,true,"Caue_Items_Eat",""],
    ["burger_full_burnt","Hambúrguer de peixe queimado",1,"A3PL_Burger_Full",0,true,true,"Caue_Items_Eat",""],
    ["corn","Espiga de milho",2,"A3PL_CornCob",0,true,true,"Caue_Items_Eat",""],
    ["lettuce","Alface",2,"A3PL_LettuceItem",0,true,true,"Caue_Items_Eat",""],
    ["Salad","Salada",1,"A3PL_Salad",0,true,true,"Caue_Items_Eat",""],
    ["tacoshell","Casca de taco",1,"A3PL_TacoShell",0,true,true,"Caue_Items_Eat",""],
    ["taco_raw","Taco de peixe cru",1,"A3PL_Taco",0,true,true,"Caue_Items_Eat",""],
    ["taco_cooked","Taco De Peixe Cozido",1,"A3PL_Taco",0,true,true,"Caue_Items_Eat",""],
    ["taco_burned","Taco De Peixe Queimado",1,"A3PL_Taco",0,true,true,"Caue_Items_Eat",""],
    ["fish_raw","Peixe cru (taco hell)",1,"A3PL_Fish_Raw",0.5,true,true,"Caue_Items_Eat",""],
    ["fish_cooked","Peixe cozido",0.5,"A3PL_Fish_Cooked",0,true,true,"Caue_Items_Eat",""],
    ["fish_burned","Peixe queimado",0.5,"A3PL_Fish_Burned",0,true,true,"Caue_Items_Eat",""],

    /* Drinks */
    ["coke","Coca-Cola",0.5,"A3PL_Can_V2",0,true,true,"Caue_Items_Drink",""],

    /* Misc */
    ["dildo","Consolo",5,"A3PL_Dildo",0,true,true,"",""],
    ["lockpick","Chave Mestra",5,"A3PL_Screwdriver_V1",0,true,true,"",""],
    ["distillery","Destilaria",10,"A3PL_Distillery",0,false,false,"",""],
    ["distillery_hose","Mangueira da destilaria",10,"A3PL_Distillery_Hose",0,false,false,"",""],
    ["jug","Jarro",1,"A3PL_Jug",0,true,true,"",""],
    ["jug_moonshine","Jarro (contém moonshine)",1,"A3PL_Jug_Corked",0,true,true,"",""],
    ["jug_green","Jarro (verde)",1,"A3PL_Jug_Green",0,true,true,"",""],
    ["jug_green_moonshine","Jarro (contém moonshine de maçã)",1,"A3PL_Jug_Green_Corked",0,true,true,"",""],
    ["malt","Malte",10,"A3PL_Grainsack_Malt",0,false,false,"",""],
    ["yeast","Fermento",10,"A3PL_Grainsack_Yeast",0,false,false,"",""],
    ["cornmeal","Fubá",10,"A3PL_Grainsack_CornMeal",0,false,false,"",""],
    ["wheat","Trigo",1,"A3PL_Sack",0,true,true,"",""],
    ["log","Tora de madeira",5,"A3PL_WoodenLog",0,false,false,"",""],
    ["bin","Lixeira",5,"A3PL_WheelieBin",0,false,false,"",""],
    ["planter","Vaso",0.1,"A3PL_Planter2",0,false,false,"",""],
    ["workbench","Bancada de Trabalho",0.1,"A3PL_WorkBench",0,false,true,"",""],
    ["lamp_200w","Lâmpada 200W",0.1,"A3PL_Cannabis_Lamp_200W",0,false,true,"",""],
    ["lamp_500w","Lâmpada 500W",0.1,"A3PL_Cannabis_Lamp_500W",0,false,true,"",""],
    ["lamp_1000w","Lâmpada 1000W",0.1,"A3PL_Cannabis_Lamp_1000W",0,false,true,"",""],
    ["fan","Ventilador",0.1,"A3PL_Fan",0,false,false,"",""],
    ["grinder","Triturador",0.1,"A3PL_Mixer",0,false,false,"",""],
    ["scale","Scale",0.1,"A3PL_Scale",0,false,false,"",""],
    ["pavilion","Pavilion",0.1,"A3PL_Pavilion",0,true,false,false,"",""],
    ["cannabis_bud","Erva de Cannabis",0.25,"A3PL_Cannabis_Bud",0,true,true,"",""],
    ["cannabis_bud_cured","Erva de Cannabis Seca",0.25,"A3PL_Cannabis_Bud",0,true,true,"",""],
    ["marijuana","Maconha",1,"A3PL_MarijuanaBag",0,true,true,"",""],
    ["cannabis_grinded_5g","Cannabis moída",0.25,"A3PL_Cannabis_Bud",0,true,true,"",""],
    ["blunt","Maconha",1,"A3PL_MarijuanaBag",90,true,true,"A3PL_Drugs_Use",""],
    ["weed_5g","Maconha (5 gramas)",1,"A3PL_MarijuanaBag",90,true,true,"",""],
    ["weed_10g","Maconha (10 gramas)",1,"A3PL_MarijuanaBag",90,true,true,"",""],
    ["weed_15g","Maconha (15 gramas)",1,"A3PL_MarijuanaBag",90,true,true,"",""],
    ["weed_20g","Maconha (20 gramas)",1,"A3PL_MarijuanaBag",90,true,true,"",""],
    ["weed_25g","Maconha (25 gramas)",1,"A3PL_MarijuanaBag",90,true,true,"",""],
    ["weed_30g","Maconha (30 gramas)",1,"A3PL_MarijuanaBag",90,true,true,"",""],
    ["weed_35g","Maconha (35 gramas)",1,"A3PL_MarijuanaBag",90,true,true,"",""],
    ["weed_40g","Maconha (40 gramas)",1,"A3PL_MarijuanaBag",90,true,true,"",""],
    ["weed_45g","Maconha (45 gramas)",1,"A3PL_MarijuanaBag",90,true,true,"",""],
    ["weed_50g","Maconha (50 gramas)",1,"A3PL_MarijuanaBag",90,true,true,"",""],
    ["weed_55g","Maconha (55 gramas)",1,"A3PL_MarijuanaBag",90,true,true,"",""],
    ["weed_60g","Maconha (60 gramas)",1,"A3PL_MarijuanaBag",90,true,true,"",""],
    ["weed_65g","Maconha (65 gramas)",1,"A3PL_MarijuanaBag",90,true,true,"",""],
    ["weed_70g","Maconha (70 gramas)",1,"A3PL_MarijuanaBag",90,true,true,"",""],
    ["weed_75g","Maconha (75 gramas)",1,"A3PL_MarijuanaBag",90,true,true,"",""],
    ["weed_80g","Maconha (80 gramas)",1,"A3PL_MarijuanaBag",90,true,true,"",""],
    ["weed_85g","Maconha (85 gramas)",1,"A3PL_MarijuanaBag",90,true,true,"",""],
    ["weed_90g","Maconha (90 gramas)",1,"A3PL_MarijuanaBag",90,true,true,"",""],
    ["weed_95g","Maconha (95 gramas)",1,"A3PL_MarijuanaBag",90,true,true,"",""],
    ["weed_100g","Maconha (100 gramas)",1,"A3PL_MarijuanaBag",90,true,true,"",""],
    ["roadcones","Cones",0.1,"A3PL_RoadCone_x10",0,false,true,"",""],
    ["roadbarrier","Barreira",0.1,"A3PL_PlasticBarrier_02",0,false,true,"",""],
    ["roadcone","Cone",0.1,"A3PL_RoadCone",0,false,false,"",""],
    ["seed_coca","Sementes de coca",0.5,"A3PL_Seed_Corn",0,true,true,"",""],
    ["seed_sugar","Sementes de cana de açúcar",0.5,"A3PL_Seed_Corn",0,true,true,"",""],
    ["coca","Coca",0.5,"A3PL_Seed_Corn",0,true,true,"",""],
    ["sugarcane","Cana de açúcar",0.5,"A3PL_Seed_Corn",0,true,true,"",""],
    ["jerrycan","Jerry Can",10,"A3PL_Jerrycan",-90,true,true,"",""],
    ["cauldron","Cauldron",0.1,"A3PL_hw_cauldron",0,false,false,"",""],
    ["skeletoncauldron","Skeleton with Cauldron",0.1,"Land_A3PL_hw_skeletonCauldron",0,false,false,"",""],
    ["lantern","Lanterna",0.1,"A3PL_hw_lantern",0,true,true,"",""],
    ["pumpkin_green","Abobora Verde",0.1,"Land_A3PL_hw_pumpkin_green",0,false,false,"",""],
    ["pumpkin_orange","Abobora Laranja",0.1,"Land_A3PL_hw_pumpkin_orange",0,false,false,"",""],
    ["pumpkin_red","Pumpkin Red",0.1,"Land_A3PL_hw_pumpkin_red",0,false,false,"",""],
    ["pumpkinhat_red","Pumpkin Hat Red",0.1,"Land_A3PL_hw_pumpkinhat_red",0,false,false,"",""],
    ["pumpkinhat_orange","Pumpkin Hat Orange",0.1,"Land_A3PL_hw_pumpkinhat_orange",0,false,false,"",""],
    ["pumpkinhat_green","Pumpkin Hat Green",0.1,"Land_A3PL_hw_pumpkinhat_green",0,false,false,"",""],
    ["girlstatue","Girl Statue",0.1,"Land_A3PL_Girlstatue",0,false,false,"",""],
    ["diamond","Diamante",0.5,"A3PL_Diamond",0,true,true,"",""],
    ["diamond_alex","Alexandrita",0.5,"A3PL_Diamond_Alex",0,true,true,"",""],
    ["diamond_aqua","Aquamarine",0.5,"A3PL_Diamond_Aqua",0,true,true,"",""],
    ["diamond_emerald","Esmeralda",0.5,"A3PL_Diamond_Emerald",0,true,true,"",""],
    ["diamond_ruby","Rubi",0.5,"A3PL_Diamond_Ruby",0,true,true,"",""],
    ["diamond_sapphire","Safira",0.5,"A3PL_Diamond_Sapphire",0,true,true,"",""],
    ["diamond_tourmaline","Turmalina",0.5,"A3PL_Diamond_Tourmaline",0,true,true,"",""],
    ["diamond_ill","Diamante Roubado",0.5,"A3PL_Diamond",0,true,true,"",""],
    ["diamond_alex_ill","Alexandrita Roubada",0.5,"A3PL_Diamond_Alex",0,true,true,"",""],
    ["diamond_aqua_ill","Aquamarine Roubada",0.5,"A3PL_Diamond_Aqua",0,true,true,"",""],
    ["diamond_emerald_ill","Emeralda Roubada",0.5,"A3PL_Diamond_Emerald",0,true,true,"",""],
    ["diamond_ruby_ill","Rubi Roubado",0.5,"A3PL_Diamond_Ruby",0,true,true,"",""],
    ["diamond_sapphire_ill","Safira Roubada",0.5,"A3PL_Diamond_Sapphire",0,true,true,"",""],
    ["diamond_tourmaline_ill","Turmalina Roubada",0.5,"A3PL_Diamond_Tourmaline",0,true,true,"",""],
    ["furn_chair1","inh",6,"A3PL_Chair1",0,false,false,"",""],
    ["furn_chair2","inh",6,"A3PL_Chair2",0,false,false,"",""],
    ["furn_chair3","inh",6,"A3PL_Chair3",0,false,false,"",""],
    ["furn_chair4","inh",6,"A3PL_Chair4",0,false,false,"",""],
    ["furn_bed1","inh",6,"A3PL_Bed1",0,false,false,"",""],
    ["furn_bed2","inh",6,"A3PL_Bed2",0,false,false,"",""],
    ["furn_cabinet1","inh",6,"A3PL_Cabinet1",0,false,false,"",""],
    ["furn_cabinet2","inh",6,"A3PL_Cabinet2",0,false,false,"",""],
    ["furn_cabinet3","inh",6,"A3PL_Cabinet3",0,false,false,"",""],
    ["furn_coffeetable1","inh",6,"A3PL_coffeeTable1",0,false,false,"",""],
    ["furn_coffeetable2","inh",6,"A3PL_coffeeTable2",0,false,false,"",""],
    ["furn_coffeetable3","inh",6,"A3PL_coffeeTable3",0,false,false,"",""],
    ["furn_coffeetable4","inh",6,"A3PL_coffeeTable4",0,false,false,"",""],
    ["furn_cornersofa","inh",6,"A3PL_CornerSova",0,false,false,"",""],
    ["furn_dryingtowel","inh",6,"A3PL_DryingTowel",0,false,false,"",""],
    ["furn_flasket","inh",6,"A3PL_Flasket",0,false,false,"",""],
    ["furn_kitchenchair1","inh",6,"A3PL_KitchenChair1",0,false,false,"",""],
    ["furn_kitchenchair2","inh",6,"A3PL_KitchenChair2",0,false,false,"",""],
    ["furn_kitchenshelf1","inh",6,"A3PL_KitchenShelf1",0,false,false,"",""],
    ["furn_kitchenshelf2","inh",6,"A3PL_KitchenShelf2",0,false,false,"",""],
    ["furn_kitchenshelf3","inh",6,"A3PL_KitchenShelf3",0,false,false,"",""],
    ["furn_kitchenshelfcorner","inh",6,"A3PL_KitchenShelfCorner",0,false,false,"",""],
    ["furn_kitchentable1","inh",6,"A3PL_KitchenTable1",0,false,false,"",""],
    ["furn_kitchentable2","inh",6,"A3PL_KitchenTable2",0,false,false,"",""],
    ["furn_lamp1","inh",6,"A3PL_Lamp1",0,false,false,"",""],
    ["furn_lamp2","inh",6,"A3PL_Lamp2",0,false,false,"",""],
    ["furn_mirror","inh",6,"A3PL_Mirror",0,false,false,"",""],
    ["furn_modkitchen1","inh",6,"A3PL_ModularKitchen1",0,false,false,"",""],
    ["furn_modkitchen2","inh",6,"A3PL_ModularKitchen2",0,false,false,"",""],
    ["furn_modkitchen3","inh",6,"A3PL_ModularKitchen3",0,false,false,"",""],
    ["furn_modkitchen4","inh",6,"A3PL_ModularKitchen4",0,false,false,"",""],
    ["furn_pouf","inh",6,"A3PL_Pouf",0,false,false,"",""],
    ["furn_rack1","inh",6,"A3PL_Rack1",0,false,false,"",""],
    ["furn_rack2","inh",6,"A3PL_Rack2",0,false,false,"",""],
    ["furn_sofa4","inh",6,"A3PL_Sofa1",0,false,false,"",""],
    ["furn_sofa5","inh",6,"A3PL_Sofa2",0,false,false,"",""],
    ["furn_sofa6","inh",6,"A3PL_Sofa3",0,false,false,"",""],
    ["furn_sofa7","inh",6,"A3PL_Sofa4",0,false,false,"",""],
    ["furn_table1","inh",6,"A3PL_table1",0,false,false,"",""],
    ["furn_table2","inh",6,"A3PL_table2",0,false,false,"",""],
    ["furn_tvtable1","inh",6,"A3PL_TvTable1",0,false,false,"",""],
    ["furn_tvtable2","inh",6,"A3PL_TvTable2",0,false,false,"",""],
    ["furn_tvtable3","inh",6,"A3PL_TvTable3",0,false,false,"",""],
    ["furn_bed3","inh",6,"A3PL_Bed3",0,false,false,"",""],
    ["furn_barcabinet","inh",6,"A3PL_Bar_Cabinet",0,false,false,"",""],
    ["furn_bookshelf","inh",6,"A3PL_Bookshelf",0,false,false,"",""],
    ["furn_diningchair","inh",6,"A3PL_DiningChair",0,false,false,"",""],
    ["furn_diningtableprops","inh",6,"A3PL_DiningTableProps",0,false,false,"",""],
    ["furn_kennel","inh",6,"A3PL_Kennel",0,false,false,"",""],
    ["furn_nightstand","inh",6,"A3PL_NightStand",0,false,false,"",""],
    ["furn_nightstandlamp","inh",6,"A3PL_NightStandLamp",0,false,false,"",""],
    ["furn_sofa1","inh",6,"A3PL_Sofa1New",0,false,false,"",""],
    ["furn_sofa3","inh",6,"A3PL_Sofa3New",0,false,false,"",""],
    ["furn_grill","inh",6,"A3PL_Mcfisher_Grill",0,false,false,"",""],
    ["furn_cabinetdoubletop","inh",6,"A3PL_CabinetDoubleTop",0,false,false,"",""],
    ["furn_cabinetsingletop","inh",6,"A3PL_CabinetSingleTop",0,false,false,"",""],
    ["furn_cabinettopcorner","inh",6,"A3PL_CabinetTopCorner",0,false,false,"",""],
    ["furn_countercorner","inh",6,"A3PL_CounterCorner",0,false,false,"",""],
    ["furn_counterdoublecabinet","inh",6,"A3PL_CounterDoubleCabinet",0,false,false,"",""],
    ["furn_counterdrawer","inh",6,"A3PL_CounterDrawer",0,false,false,"",""],
    ["furn_countersinglecabinet","inh",6,"A3PL_CounterSingleCabinet",0,false,false,"",""],
    ["furn_countertop1","inh",6,"A3PL_CounterTop1",0,false,false,"",""],
    ["furn_countertop2","inh",6,"A3PL_CounterTop2",0,false,false,"",""],
    ["furn_countertop3","inh",6,"A3PL_CounterTop3",0,false,false,"",""],
    ["furn_sinkbigcounter","inh",6,"A3PL_SinkBigCounter",0,false,false,"",""],
    ["furn_sinksinglecabinet","inh",6,"A3PL_SinkSingleCabinet",0,false,false,"",""],
    ["taxidriver","Dinheiro",0,"A3PL_Money",0,true,true,"",""],
    ["waterbottle","Garrafa de Agua",1,"Land_BottlePlastic_V2_F",90,true,true,"",""],
    ["handcuffs","Algemas",1,"A3PL_Handcuffs",0,true,true,"",""],
    ["rope","Corda",5,"Land_Rope_01_F",90,true,true,"",""],
    ["Lifebuoy","Boia salva-vidas",1,"A3PL_Lifebuoy",0,true,true,"",""],
    ["meat_goat","Carne de cabra",0.5,"A3PL_Steak",90,true,true,"",""],
    ["meat_sheep","Carne de ovelha",0.5,"A3PL_Steak",90,true,true,"",""],
    ["meat_boar","Carne de javali",0.5,"A3PL_Steak",90,true,true,"",""],
    ["meat_goat_tag","Carne de cabra (marcada)",0.5,"A3PL_Steak",90,true,true,"",""],
    ["meat_sheep_tag","Carne de ovelha (marcada)",0.5,"A3PL_Steak",90,true,true,"",""],
    ["meat_boar_tag","Carne de javali (marcada)",0.5,"A3PL_Steak",90,true,true,"",""],
    ["tag_meat","Etiqueta de Carne",0.1,"A3PL_File2",0,true,true,"",""],
    ["tag_shark","Etiqueta de Tubarão",0.1,"A3PL_File2",0,true,true,"",""],
    ["tag_fish","Etiqueta de Peixe",0.1,"A3PL_File2",0,true,true,"",""],
    ["mullet","Tainha",0.5,"A3PL_Mullet",90,true,true,"",""],
    ["mullet_tag","Tainha (marcada)",0.5,"A3PL_Mullet",90,true,true,"",""],
    ["shark_2lb","Catshark - 2LB",2,"A3PL_CatShark",90,true,true,"",""],
    ["shark_2lb_tag","Catshark - 2LB (tagged)",2,"A3PL_CatShark",90,true,true,"",""],
    ["shark_4lb","Catshark - 4LB",4,"A3PL_CatShark",90,true,true,"",""],
    ["shark_4lb_tag","Catshark - 4LB (tagged)",4,"A3PL_CatShark",90,true,true,"",""],
    ["shark_5lb","Catshark - 5LB",5,"A3PL_CatShark",90,true,true,"",""],
    ["shark_5lb_tag","Catshark - 5LB (tagged)",5,"A3PL_CatShark",90,true,true,"",""],
    ["shark_7lb","Catshark - 7LB",7,"A3PL_CatShark",90,true,true,"",""],
    ["shark_7lb_tag","Catshark - 7LB (tagged)",7,"A3PL_CatShark",90,true,true,"",""],
    ["shark_10lb","Catshark - 10LB",10,"A3PL_CatShark",90,true,true,"",""],
    ["shark_10lb_tag","Catshark - 10LB (tagged)",10,"A3PL_CatShark",90,true,true,"",""],
    ["turtle","Tartaruga",2,"A3PL_Ornate",90,true,true,"",""],
    ["Meat_Scraps","Restos de carne",0.5,"A3PL_Burger_Raw",90,true,true,"",""],
    ["net","Rede de Pesca",1,"A3PL_FishingBuoy",0,true,true,"",""],
    ["bucket_empty","Balde vazio",1,"A3PL_Bucket",0,true,true,"",""],
    ["bucket_full","Balde de peixe",1,"A3PL_BucketFull",0,true,true,"",""],
    ["repairwrench","Chave de reparo",0.5,"A3PL_Wrench",0,true,true,"",""],
    ["ticket","Multa",0.1,"A3PL_Ticket",0,false,true,"",""],
    ["Ladder","Escada",5,"A3PL_Ladder",0,false,false,"",""],
    ["drill_bit","Broca",0.1,"A3PL_Drill_Bit",0,true,true,"",""],
    ["stinger","Tapete de espinhos",0.1,"A3PL_Stinger",0,true,true,"",[2,0.5,0],"",""],
    ["seed_wheat","Sementes de trigo",0.5,"A3PL_Seed_Wheat",0,true,true,"",""],
    ["seed_corn","Sementes de milho",0.5,"A3PL_Seed_Corn",0,true,true,"",""],
    ["seed_marijuana","Sementes de maconha",0.5,"A3PL_Seed_Marijuana",0,true,true,"",""],
    ["seed_lettuce","Sementes de alface",0.5,"A3PL_Seed_Lettuce",0,true,true,"",""],
    ["beer","Cerveja Corona",0.1,"A3PL_Corona",180,true,true,"A3PL_Drugs_Use",[-0.03,-0.05,0.1],"",""],
    ["beer_gold","XXXX Cerveja Dourada",0.1,"A3PL_4xGold",180,true,true,"A3PL_Drugs_Use",""],
    ["cocaine","Cocaína",0.1,"A3PL_PowderedMilk",0,true,true,"A3PL_Drugs_Use",""],
    ["shrooms","Cogumelos",0.1,"A3PL_TacticalBacon",0,true,true,"A3PL_Drugs_Use",""],
    ["popcornbucket","Balde de pipoca",5,"A3PL_PopcornBucket",0,true,true,"",""],
    ["Camper_Light","Camper Light",5,"A3PL_Camping_Light",0,true,true,"",""],
    ["rocket_blue","Fogo de artificio (Azul)",2,"A3PL_Rocket",0,true,true,"",""],
    ["rocket_red","Fogo de artificio (Vermelho)",2,"A3PL_Rocket",0,true,true,"",""],
    ["rocket_green","Fogo de artificio (Verde)",2,"A3PL_Rocket",0,true,true,"",""],
    ["rocket_yellow","Fogo de artificio (Amarelo)",2,"A3PL_Rocket",0,true,true,"",""],
    ["FD_yAdapter","Adptador Y de Mangueira",1,"A3PL_FD_yAdapter",0,true,true,"",""],
    ["FD_Adapter","Adptador de Mangueira",1,"A3PL_FD_HoseEnd_Player",0,true,true,"",""],
    ["FD_Hose","Mangueira Enrolada",3,"A3PL_FD_HoseRolled",0,true,true,"",""],
    ["FD_HydrantWrench","Chave de Hidrante",3,"A3PL_FD_HydrantWrench",0,true,true,"",""],
    ["FD_Mask","Máscara de Oxigênio",2,"A3PL_FD_Mask_Obj",180,true,true,"",[-0.12,-0.15,-0.73],"",""],
    ["Pumpjack","inh",50,"A3PL_Pumpjack",0,false,false,"",""],
    ["mail","inh",0.2,"A3PL_DeliveryBox",0,false,false,"",""],
    ["Synthetic_Fibre","Fibra Sintética",0.2,"A3PL_Synthetic_Fiber",0,true,true,"",""],
    ["Nylon","Náilon",0.2,"A3PL_Nylon",0,false,false,"",""],
    ["Spandex","inh",0.2,"A3PL_Spandex",0,false,false,"",""],
    ["Polyester","Poliéster",1,"A3PL_Polyester",0,true,true,"",""],
    ["Acrylic","Acrílico",0.2,"A3PL_Acrylic",0,true,true,"",""],
    ["Rayon","Seda Artificial",0.2,"A3PL_Rayon",0,false,false,"",""],
    ["Aramid","Aramida",1,"A3PL_Aramid",0,false,false,"",""],
    ["Rubber","Borracha",0.2,"A3PL_Rubber",0,true,true,"",""],
    ["Crude_Oil","Petróleo Bruto",367,"A3PL_OilBarrel",0,false,false,"",""],
    ["LPG","Botijão",88,"A3PL_LPG",0,false,false,"",""],
    ["Petrol","Petróleo",367,"A3PL_OilBarrel",0,false,false,"",""],
    ["Kerosene","Querosene",367,"A3PL_Kerosene",0,false,false,"",""],
    ["CanisterOil","Vasilha de Óleo",4,"A3PL_CanisterOil",0,true,true,"",""],
    ["Sand","Areia",1,"A3PL_BucketSand",0,true,true,"",""],
    ["Titanium_Ore","Minério de Titânio",1,"A3PL_Titanium_Ore",0,true,true,"",""],
    ["Titanium_Ingot","Lingote de Titânio",1,"A3PL_Titanium_Ingot",0,true,true,"",""],
    ["Aluminium_Ore","Minério de Aluminio",0.25,"A3PL_Resource_Ore_Orange_Small",0,true,true,"",""],
    ["Aluminium_Ingot","Lingote de Aluminio",1,"A3PL_Aluminium_Ingot",0,true,true,"",""],
    ["Aluminium","Aluminio",1,"A3PL_Aluminium",0,true,true,"",""],
    ["Iron_Ore","Minério de Ferro",0.25,"A3PL_Resource_Ore_Pink_Small",0,true,true,"",""],
    ["Iron_Ingot","Lingote de Ferro",1,"A3PL_Iron_Ingot",0,true,true,"",""],
    ["Coal_Ore","Minério de Carvão",0.25,"A3PL_Resource_Ore_Black_Small",0,true,true,"",""],
    ["Coal_Ingot","Lingote de Carvão",1,"A3PL_Coal_Ingot",0,true,true,"",""],
    ["Sulphur_Ore","Minério de Enxofre",0.25,"A3PL_Resource_Ore_Yellow_Small",0,true,true,"",""],
    ["Sulphur_Powder","Enxofre",1,"A3PL_SulphurPowder",0,true,true,"",""],
    ["Gunpowder","Polvora",1,"A3PL_Gunpowder",0,true,true,"",""],
    ["Steel","Aço",1,"A3PL_Steel",0,true,true,"",""],
    ["Titanium","Titanio",1,"A3PL_Titanium",0,true,true,"",""],
    ["Glass_Fibre","Fibra de Vidro",1,"A3PL_Glass_Fibre",0,true,true,"",""],
    ["Glass","Vidro",1,"A3PL_Glass",0,true,true,"",""],
    ["Fibreglass","Plástico Reforçado",1,"A3PL_Fibreglass",0,true,true,"",""],
    ["Plastic","Plastico",1,"A3PL_Plastic",0,true,true,"",""],
    ["Kevlar","Kevlar",1,"A3PL_Kevlar",0,true,true,"",""],
    ["Engine","Motor",5,"A3PL_Engine",0,true,true,"",""],
    ["Trans","Transmissão",1,"A3PL_Transmission",0,true,true,"",""],
    ["Radiator","Radiador",1,"A3PL_Radiator",0,true,true,"",""],
    ["BrakeRotors","Freios",1,"A3PL_Brake_Rotor",0,true,true,"",""],
    ["Diff","Diferencial",1,"A3PL_Diff",0,true,true,"",""],
    ["FuelTank","Tanque de Combustivel",1,"A3PL_Fuel_Tank",0,true,true,"",""],
    ["Chassis","Chassi",5,"A3PL_Chassis",0,true,true,"",""],
    ["DriveShaft","Eixo de Transmissão",1,"A3PL_Drive_Shaft",0,true,true,"",""],
    ["Exhaust","Tubos de Escape",1,"A3PL_Exhaust",0,true,true,"",""],
    ["Windows","Janelas",5,"A3PL_Glass",0,true,true,"",""],
    ["HEEngine","Motor de alta potência",5,"A3PL_Engine",0,true,true,"",""],
    ["HETrans","Transmissão de alta potência",1,"A3PL_Transmission",0,true,true,"",""],
    ["HERadiator","Radiador de alta potência",1,"A3PL_Radiator",0,true,true,"",""],
    ["HERadiator","Radiador de alta potência",1,"A3PL_Radiator",0,true,true,"",""],
    ["HEBrakeRotors","Freios de alta potência",1,"A3PL_Brake_Rotor",0,true,true,"",""],
    ["HEDiff","Diferencial de alta potência",1,"A3PL_Diff",0,true,true,"",""],
    ["HEFuelTank","Tanque de Combustivel de alta potência",1,"A3PL_Fuel_Tank",0,true,true,"",""],
    ["HEChassis","Chassi de alta potência",5,"A3PL_Chassis",0,true,true,"",""],
    ["HEDriveShaft","Eixo de Transmissão de alta potência",1,"A3PL_Drive_Shaft",0,true,true,"",""],
    ["HEExhaust","Tubos de Escape de alta potência",1,"A3PL_Exhaust",0,true,true,"",""],
    ["4WDDiff","Diferencial 4x4",1,"A3PL_Diff",0,true,true,"",""],
    ["SteelRims","Aros de Aço",1,"A3PL_SteelRims",0,true,true,"",""],
    ["AlloyRims","Aros de Aluminio",1,"A3PL_AlloyRims",0,true,true,"",""],
    ["Tyres","Pneus",1,"A3PL_Tyre",0,true,true,"",""],
    ["ME_Bucket","inh",35,"A3PL_MiniExcavator_Bucket",0,true,true,"",""],
    ["ME_Jackhammer","inh",35,"A3PL_MiniExcavator_Jackhammer",0,true,true,"",""],
    ["ME_Claw","inh",35,"A3PL_MiniExcavator_Claw",0,true,true,"",""],
    ["Steel_Pellet","Pilha de Aço",6,"A3PL_Steel_Pellet",0,false,false,"",""],
    ["Aluminium_Pellet","Pilha de Aluminio",6,"A3PL_Aluminium_Pellet",0,false,false,"",""],
    ["Titanium_Pellet","Pilha de Titanio",6,"A3PL_Titanium_Pellet",0,false,false,"",""],

    /* Medical */
    ["med_cast","Atadura",0.1,"A3PL_Medical_Cast",0.1,true,true,"",""],
    ["med_endotracheal","Endotraqueal",0.1,"A3PL_Medical_Endotracheal",0,true,true,"",""],
    ["med_icepack","Bolsa de Gelo",0.1,"A3PL_Medical_Icepack",0,true,true,"",""],
    ["med_bandage","Bandagem",0.1,"A3PL_Bandage",0,true,true,"",""],
    ["med_kit","Kit Sirurgico",0.1,"A3PL_Medical_Kit",0,true,true,"",""],
    ["med_oxygenmask","Oxigênio",0.1,"A3PL_Medical_OxygenMask",0,true,true,"",""],
    ["med_splint","Tala",0.1,"A3PL_Medical_Splint",0,true,true,"",""],
    ["med_painkillers","Analgésico",0.1,"A3PL_PainKillers",0,true,true,"",""],
    ["med_autograft","inh",0.1,"A3PL_Grinder",0,true,true,"",""],
    ["medS_bloodbag","Bolsa de Sangue",0.1,"A3PL_BloodBag",0,true,true,"",""],

    /* Blueprints Vehicles */
    ["Blueprint_Boat_Civil_01_rescue","BP USCG Rescue Boat",0,"A3PL_File2",0,true,true,"",""],
    ["Blueprint_RBM","BP USCG RBM",0,"A3PL_File2",0,true,true,"",""],
    ["Blueprint_Goose","BP USCG Goose",0,"A3PL_File2",0,true,true,"",""],
    ["Blueprint_CopHeli","BP Heli Sheriff",0,"A3PL_File2",0,true,true,"",""],
    ["Blueprint_Jayhawk","BP USCG Jayhawk",0,"A3PL_File2",0,true,true,"",""],
    ["Blueprint_f450","BP EMS F450",0,"A3PL_File2",0,true,true,"",""],
    ["Blueprint_e350","BP EMS E350",0,"A3PL_File2",0,true,true,"",""],
    ["Blueprint_tahoe_FD","BP FD Tahoe",0,"A3PL_File2",0,true,true,"",""],
    ["Blueprint_ladder","BP FD Ladder Truck",0,"A3PL_File2",0,true,true,"",""],
    ["Blueprint_hladder","BP FD Heavy Ladder Truck",0,"A3PL_File2",0,true,true,"",""],
    ["Blueprint_pumper","BP FD Pumper Truck",0,"A3PL_File2",0,true,true,"",""],
    ["Blueprint_cvpi_PD","BP SD CVPI",0,"A3PL_File2",0,true,true,"",""],
    ["Blueprint_cvpi_PDST","BP SD NL CVPI",0,"A3PL_File2",0,true,true,"",""],
    ["Blueprint_tahoe_PD","BP SD Tahoe",0,"A3PL_File2",0,true,true,"",""],
    ["Blueprint_tahoe_PDST","BP SD NL Tahoe",0,"A3PL_File2",0,true,true,"",""],
    ["Blueprint_mustang_PD","BP SD Mustang",0,"A3PL_File2",0,true,true,"",""],
    ["Blueprint_mustang_PDST","BP SD NL Mustang",0,"A3PL_File2",0,true,true,"",""],
    ["Blueprint_charger_PD","BP SD Charger",0,"A3PL_File2",0,true,true,"",""],
    ["Blueprint_charger_PDST","BP SD NL Charger",0,"A3PL_File2",0,true,true,"",""],

    /* Blueprints Weapons */
    ["Blueprint_FAL","FAL Blueprint",0,"A3PL_File2",0,true,true,"",""],
    ["Blueprint_30Rnd_762x39_Mag_F","FAL Mag Blueprint",0,"A3PL_File2",0,true,true,"",""],
    ["Blueprint_MP412","MP412 Blueprint",0,"A3PL_File2",0,true,true,"",""],
    ["Blueprint_6Rnd_357_Mag",".357 Blueprint",0,"A3PL_File2",0,true,true,"",""],
    ["Blueprint_M1911A1","M1911A1 Blueprint",0,"A3PL_File2",0,true,true,"",""],
    ["Blueprint_7Rnd_45cal_m1911","M1911 mag Blueprint",0,"A3PL_File2",0,true,true,"",""],
    ["Blueprint_GSH18","GSH-18 Blueprint",0,"A3PL_File2",0,true,true,"",""],
    ["Blueprint_18Rnd_9x19_gsh","GSH-18 mag Blueprint",0,"A3PL_File2",0,true,true,"",""],
    ["Blueprint_G17","Glock 17 Blueprint",0,"A3PL_File2",0,true,true,"",""],
    ["Blueprint_17Rnd_9x19_g17","Glock17 mag Blueprint",0,"A3PL_File2",0,true,true,"",""],
    ["Blueprint_Python","Python Blueprint",0,"A3PL_File2",0,true,true,"",""],
    ["Blueprint_6Rnd_357_Mag",".357 Blueprint",0,"A3PL_File2",0,true,true,"",""]
];
publicVariable "Config_Items";

Config_Foods = [
    ["donut",2],
    ["cereal",2],
    ["burger_bun",3],
    ["burger_burnt",-10],
    ["burger_raw",-5],
    ["burger_cooked",15],
    ["burger_full_raw",-5],
    ["burger_full_cooked",40],
    ["burger_full_burnt",-20],
    ["corn",3],
    ["lettuce",3],
    ["salad",5],
    ["fish_raw",-10],
    ["fish_cooked",5],
    ["fish_burned",-12],
    ["taco_raw",-15],
    ["taco_cooked",40],
    ["taco_burned",-20],
    ["tacoshell",2],
    ["lamington",80],
    ["sausages",80],
    ["meatpie",100]
];
publicVariable "Config_Foods";

Config_Drinks = [
    ["coke",40]
];
publicVariable "Config_Drinks";

Config_Items_Illegal = [
    "seed_marijuana","marijuana","blunt","cannabis_bud","cannabis_bud_cured","cannabis_grinded_5g",
    "weed_5g","weed_10g","weed_15g","weed_20g","weed_25g","weed_30g","weed_35g","weed_40g","weed_45g","weed_50g","weed_55g","weed_60g","weed_65g","weed_70g","weed_75g","weed_80g","weed_85g","weed_90g","weed_95g","weed_100g",
    "cocaine","shrooms","jug_moonshine","jug_green_moonshine"
];
publicVariable "Config_Items_Illegal";

Config_Combine = [
    ["burger_full_cooked",[["burger_cooked",1],["burger_bun",1],["Salad",1]],1],
    ["burger_full_raw",[["burger_raw",1],["burger_bun",1],["Salad",1]],1],
    ["burger_full_burnt",[["burger_burnt",1],["burger_bun",1],["Salad",1]],1],
    ["taco_cooked",[["fish_cooked",1],["tacoshell",1],["Salad",1]],1],
    ["taco_raw",[["fish_raw",1],["tacoshell",1],["Salad",1]],1],
    ["taco_burned",[["fish_burned",1],["tacoshell",1],["Salad",1]],1],

    ["meat_goat_tag",[["meat_goat",1],["tag_meat",1]],1],
    ["meat_sheep_tag",[["meat_sheep",1],["tag_meat",1]],1],
    ["meat_boar_tag",[["meat_boar",1],["tag_meat",1]],1],

    ["mullet_tag",[["mullet",1],["tag_fish",1]],1],
    ["shark_2lb_tag",[["shark_2lb",1],["tag_shark",1]],1],
    ["shark_4lb_tag",[["shark_4lb",1],["tag_shark",1]],1],
    ["shark_5lb_tag",[["shark_5lb",1],["tag_shark",1]],1],
    ["shark_7lb_tag",[["shark_7lb",1],["tag_shark",1]],1],
    ["shark_10lb_tag",[["shark_10lb",1],["tag_shark",1]],1]
];
publicVariable "Config_Combine";
