Config_Shop_Clothing = [
    ["Loja de Roupas",[
        /* Uniforms */
        ["uniform","U_I_C_Soldier_Bandit_3_F",100,"true"],
        ["uniform","U_I_C_Soldier_Bandit_4_F",100,"true"],
        ["uniform","U_I_C_Soldier_Bandit_5_F",100,"true"],
        ["uniform","A3PL_GreenPlad_Shirt_Uniform",100,"true"],
        ["uniform","A3PL_Worker_Uniform",100,"true"],

        ["uniform","A3PL_Hoodie_Uniform",100,"true"],
        ["uniform","A3PL_citizen4_Uniform",100,"true"],

        ["uniform","d3s_uniform_jbib_008_a",100,"true"],
        ["uniform","d3s_uniform_jbib_008_b",100,"true"],
        ["uniform","d3s_uniform_jbib_008_c",100,"true"],
        ["uniform","d3s_uniform_jbib_008_d",100,"true"],
        ["uniform","d3s_uniform_jbib_008_e",100,"true"],
        ["uniform","d3s_uniform_jbib_008_f",100,"true"],
        ["uniform","d3s_uniform_jbib_008_g",100,"true"],
        ["uniform","d3s_uniform_jbib_008_h",100,"true"],
        ["uniform","d3s_uniform_jbib_008_i",100,"true"],
        ["uniform","d3s_uniform_jbib_008_j",100,"true"],
        ["uniform","d3s_uniform_jbib_008_k",100,"true"],
        ["uniform","d3s_uniform_jbib_008_l",100,"true"],
        ["uniform","d3s_uniform_jbib_008_m",100,"true"],
        ["uniform","d3s_uniform_jbib_008_n",100,"true"],
        ["uniform","d3s_uniform_jbib_008_o",100,"true"],

        ["uniform","KAEL_SUITS_BR_F24",2000,"true"],
        ["uniform","KAEL_SUITS_BR_F25",2000,"true"],
        ["uniform","KAEL_SUITS_BR_F16",2000,"true"],
        ["uniform","KAEL_SUITS_BR_F17",2000,"true"],
        ["uniform","KAEL_SUITS_BR_F18",2000,"true"],
        ["uniform","KAEL_SUITS_BR_F19",2000,"true"],
        ["uniform","KAEL_SUITS_BR_F20",2000,"true"],
        ["uniform","KAEL_SUITS_BR_F21",2000,"true"],
        ["uniform","KAEL_SUITS_BR_F22",2000,"true"],
        ["uniform","KAEL_SUITS_BR_F23",2000,"true"],
        ["uniform","KAEL_SUITS_BR_F15",2000,"true"],
        ["uniform","KAEL_SUITS_BR_F26",2000,"true"],
        ["uniform","KAEL_SUITS_BR_F27",2000,"true"],
        ["uniform","KAEL_SUITS_BR_F28",2000,"true"],
        ["uniform","KAEL_SUITS_BR_F29",2000,"true"],
        ["uniform","KAEL_SUITS_BR_F30",2000,"true"],
        ["uniform","KAEL_SUITS_BR_F31",2000,"true"],
        ["uniform","KAEL_SUITS_BR_F32",2000,"true"],
        ["uniform","KAEL_SUITS_BR_F33",2000,"true"],
        ["uniform","KAEL_SUITS_BR_F34",2000,"true"],
        ["uniform","KAEL_SUITS_BR_F35",2000,"true"],
        ["uniform","KAEL_SUITS_BR_F3",2000,"true"],
        ["uniform","KAEL_SUITS_BR_F12",2000,"true"],
        ["uniform","KAEL_SUITS_BR_F8",2000,"true"],
        ["uniform","KAEL_SUITS_BLK_F",2000,"true"],
        ["uniform","KAEL_SUITS_BR_F11",2000,"true"],
        ["uniform","KAEL_SUITS_BR_F10",2000,"true"],
        ["uniform","KAEL_SUITS_BR_F7",2000,"true"],
        ["uniform","KAEL_SUITS_BR_F6",2000,"true"],
        ["uniform","KAEL_SUITS_BR_F5",2000,"true"],
        ["uniform","KAEL_SUITS_BR_F4",2000,"true"],
        ["uniform","KAEL_SUITS_BR_F",2000,"true"],
        ["uniform","KAEL_SUITS_BR_F9",2000,"true"],
        ["uniform","KAEL_SUITS_BR_F13",2000,"true"],
        ["uniform","KAEL_SUITS_BR_F14",2000,"true"],

        ["uniform","A3PL_Blackwater_White_Uniform",100,"true"],
        ["uniform","A3PL_SuitBrwBlu_Uniform",100,"true"],
        ["uniform","A3PL_CCP_Candidate_Uniform",100,"true"],
        ["uniform","A3PL_CGIS_Suit_Uniform",100,"true"],
        ["uniform","A3PL_Mafia_Lead_Uniform",100,"true"],
        ["uniform","A3PL_Mafia_Uniform",100,"true"],
        ["uniform","A3PL_Nob_Hill_Furnish_Uniform",100,"true"],
        ["uniform","A3PL_Nikos_Aged_Uniform",100,"true"],
        ["uniform","A3PL_SuitRedTie_Uniform",100,"true"],
        ["uniform","A3PL_White_Dress_Uniform",100,"true"],

        ["uniform","sl_client_c_civil01_01_W",100,"true"],
        ["uniform","sl_client_c_civil01_02_W",100,"true"],
        ["uniform","sl_client_c_civil01_03_W",100,"true"],
        ["uniform","sl_client_c_civil01_04_W",100,"true"],
        ["uniform","sl_client_c_civil01_05_W",100,"true"],
        ["uniform","sl_client_c_civil01_06_W",100,"true"],
        ["uniform","sl_client_c_civil01_07_W",100,"true"],
        ["uniform","sl_client_c_civil01_08_W",100,"true"],
        ["uniform","sl_client_c_civil01_09_W",100,"true"],
        ["uniform","sl_client_c_civil01_10_W",100,"true"],

        ["uniform","sl_client_c_civil02_01_W",100,"true"],
        ["uniform","sl_client_c_civil02_02_W",100,"true"],
        ["uniform","sl_client_c_civil02_03_W",100,"true"],
        ["uniform","sl_client_c_civil02_04_W",100,"true"],
        ["uniform","sl_client_c_civil02_05_W",100,"true"],
        ["uniform","sl_client_c_civil02_06_W",100,"true"],
        ["uniform","sl_client_c_civil02_07_W",100,"true"],
        ["uniform","sl_client_c_civil02_08_W",100,"true"],

        ["uniform","sl_client_c_civil03_01_W",100,"true"],
        ["uniform","sl_client_c_civil03_02_W",100,"true"],
        ["uniform","sl_client_c_civil03_03_W",100,"true"],
        ["uniform","sl_client_c_civil03_04_W",100,"true"],
        ["uniform","sl_client_c_civil03_05_W",100,"true"],
        ["uniform","sl_client_c_civil03_06_W",100,"true"],
        ["uniform","sl_client_c_civil03_07_W",100,"true"],

        ["uniform","sl_client_c_civil04_01_W",100,"true"],

        ["uniform","sl_client_c_civil05_01_W",100,"true"],
        ["uniform","sl_client_c_civil05_02_W",100,"true"],
        ["uniform","sl_client_c_civil05_03_W",100,"true"],
        ["uniform","sl_client_c_civil05_04_W",100,"true"],
        ["uniform","sl_client_c_civil05_05_W",100,"true"],
        ["uniform","sl_client_c_civil05_06_W",100,"true"],
        ["uniform","sl_client_c_civil05_07_W",100,"true"],

        ["uniform","sl_client_c_civil06_01_W",100,"true"],
        ["uniform","sl_client_c_civil06_02_W",100,"true"],
        ["uniform","sl_client_c_civil06_03_W",100,"true"],
        ["uniform","sl_client_c_civil06_04_W",100,"true"],
        ["uniform","sl_client_c_civil06_05_W",100,"true"],

        ["uniform","sl_client_c_executivesuit_W",100,"true"],
        ["uniform","sl_client_c_priest_W",100,"true"],
        ["uniform","sl_client_c3_ls_mechanic_W",100,"true"],

        ["uniform","sl_client_c_jackoy1_W",100,"true"],
        ["uniform","sl_client_c_jackoy2_W",100,"true"],
        ["uniform","sl_client_c_jackoy3_W",100,"true"],
        ["uniform","sl_client_c_jackoy4_W",100,"true"],
        ["uniform","sl_client_c_jackoy5_W",100,"true"],
        ["uniform","sl_client_c_jackoy6_W",100,"true"],
        ["uniform","sl_client_c_jackoy7_W",100,"true"],
        ["uniform","sl_client_c_jackoy8_W",100,"true"],

        ["uniform","A3PL_JurasGolf_BluBlk_Uniform",100,"true"],
        ["uniform","A3PL_JurasGolf_RdBlk_Uniform",100,"true"],
        ["uniform","A3PL_JurasGolf_RdBlkTrws_Uniform",100,"true"],
        ["uniform","A3PL_JurasGolf_WhtBlkTrws_Uniform",100,"true"],

        ["uniform","A3PL_LVPolo_Uniform",10000,"true"],
        ["uniform","A3PL_Nike_Black_Uniform",100,"true"],
        ["uniform","A3PL_Nike_SB_Uniform",100,"true"],
        ["uniform","A3PL_Nikos_Uniform",100,"true"],
        ["uniform","A3PL_Ripcurl_Black_Uniform",100,"true"],
        ["uniform","A3PL_Rocket_Uniform",100,"true"],
        ["uniform","A3PL_Supreme_Casual_Uniform",5000,"true"],
        ["uniform","A3PL_Supreme_Casual_Logo_2_Uniform",5000,"true"],
        ["uniform","A3PL_White_Uniform",100,"true"],

        ["uniform","A3PL_Lumberjack_Uniform",100,"true"],
        ["uniform","A3PL_Lumberjack_Blue_Uniform",100,"true"],
        ["uniform","A3PL_Lumberjack_Green_Uniform",100,"true"],

        ["uniform","A3PL_Mining_Uniform",100,"true"],
        ["uniform","A3PL_Oil_Recovery_Uniform",100,"true"],
        ["uniform","A3PL_CamelTow_Uniform",100,"true"],

        ["uniform","sl_client_c4_rocker_W",100,"true"],
        ["uniform","sl_client_c4_rocker2_W",100,"true"],
        ["uniform","sl_client_c4_rocker3_W",100,"true"],
        ["uniform","sl_client_c4_rocker4_W",100,"true"],

        ["uniform","sl_client_c_suit_W_0_D",100,"true"],
        ["uniform","sl_client_c_suit_W_0_D1",100,"true"],
        ["uniform","sl_client_c_suit_W_0_D1M",100,"true"],
        ["uniform","sl_client_c_suit_W_0_D1M1",100,"true"],
        ["uniform","sl_client_c_suit_W_0_D1M2",100,"true"],
        ["uniform","sl_client_c_suit_W_0_D1M3",100,"true"],

        ["uniform","sl_client_c_nigga1_black_W",100,"true"],
        ["uniform","sl_client_c_nigga2_black_W",100,"true"],
        ["uniform","sl_client_c_nigga1_blue_W",100,"true"],
        ["uniform","sl_client_c_nigga2_blue_W",100,"true"],
        ["uniform","sl_client_c_nigga1_green_W",100,"true"],
        ["uniform","sl_client_c_nigga2_green_W",100,"true"],
        ["uniform","sl_client_c_nigga1_multi_W",100,"true"],
        ["uniform","sl_client_c_nigga2_multi_W",100,"true"],
        ["uniform","sl_client_c_nigga1_red_W",100,"true"],
        ["uniform","sl_client_c_nigga2_red_W",100,"true"],
        ["uniform","sl_client_c_nigga1_white_W",100,"true"],
        ["uniform","sl_client_c_nigga2_white_W",100,"true"],

        ["uniform","TRYK_U_B_fleece",100,"true"],
        ["uniform","TRYK_U_B_fleece_UCP",100,"true"],
        ["uniform","TRYK_U_Bts_PCUs",100,"true"],
        ["uniform","TRYK_U_Bts_PCUGs",100,"true"],
        ["uniform","TRYK_U_Bts_GRYGRY_PCUs",100,"true"],
        ["uniform","TRYK_U_Bts_Wood_PCUs",100,"true"],
        ["uniform","TRYK_U_Bts_PCUODs",100,"true"],
        ["uniform","TRYK_U_B_PCUHs",100,"true"],
        ["uniform","TRYK_U_B_PCUGHs",100,"true"],
        ["uniform","TRYK_U_B_PCUODHs",100,"true"],
        ["uniform","TRYK_U_B_PCUGs_BLK_R",100,"true"],
        ["uniform","TRYK_U_B_PCUGs_gry_R",100,"true"],
        ["uniform","TRYK_U_B_PCUGs_OD_R",100,"true"],
        ["uniform","TRYK_U_B_PCUGs_BLK",100,"true"],
        ["uniform","TRYK_U_B_PCUGs_OD",100,"true"],
        ["uniform","TRYK_U_denim_hood_mc",100,"true"],
        ["uniform","TRYK_U_denim_hood_nc",100,"true"],
        ["uniform","TRYK_U_denim_hood_3c",100,"true"],

        ["uniform","TRYK_shirts_DENIM_BK",100,"true"],
        ["uniform","TRYK_shirts_DENIM_BL",100,"true"],
        ["uniform","TRYK_shirts_DENIM_BWH",100,"true"],
        ["uniform","TRYK_shirts_DENIM_od",100,"true"],
        ["uniform","TRYK_shirts_DENIM_R",100,"true"],
        ["uniform","TRYK_shirts_DENIM_RED2",100,"true"],
        ["uniform","TRYK_shirts_DENIM_WH",100,"true"],
        ["uniform","TRYK_shirts_DENIM_WHB",100,"true"],
        ["uniform","TRYK_shirts_DENIM_ylb",100,"true"],

        ["uniform","TRYK_OVERALL_SAGE_BLKboots_nk_blk2",100,"true"],
        ["uniform","TRYK_OVERALL_nok_flesh",100,"true"],

        ["uniform","TRYK_U_denim_jersey_blk",100,"true"],
        ["uniform","TRYK_U_denim_jersey_blu",100,"true"],

        /* Vests */
        ["vest","d3s_vest_1",100,"true"],
        ["vest","d3s_vest_1_a",100,"true"],
        ["vest","d3s_vest_1_b",100,"true"],
        ["vest","d3s_vest_1_c",100,"true"],
        ["vest","d3s_vest_1_d",100,"true"],
        ["vest","d3s_vest_1_e",100,"true"],
        ["vest","d3s_vest_1_f",100,"true"],
        ["vest","d3s_vest_1_g",100,"true"],
        ["vest","d3s_vest_1_h",100,"true"],
        ["vest","d3s_vest_1_i",100,"true"],
        ["vest","d3s_vest_1_j",100,"true"],
        ["vest","d3s_vest_1_k",100,"true"],
        ["vest","d3s_vest_1_l",100,"true"],
        ["vest","d3s_vest_1_m",100,"true"],
        ["vest","d3s_vest_1_n",100,"true"],
        ["vest","d3s_vest_1_o",100,"true"],
        ["vest","d3s_vest_1_p",100,"true"],
        ["vest","d3s_vest_1_q",100,"true"],
        ["vest","d3s_vest_1_r",100,"true"],
        ["vest","d3s_vest_1_s",100,"true"],
        ["vest","d3s_vest_1_t",100,"true"],
        ["vest","d3s_vest_1_u",100,"true"],
        ["vest","d3s_vest_1_v",100,"true"],
        ["vest","d3s_vest_1_w",100,"true"],
        ["vest","d3s_vest_1_x",100,"true"],
        ["vest","d3s_vest_1_y",100,"true"],
        ["vest","d3s_vest_1_z",100,"true"],
        ["vest","accs_diff_000",100,"true"],
        ["vest","sl_client_c_poncho_dry_W",100,"true"],
        ["vest","V_Pocketed_black_F",100,"true"],
        ["vest","V_Pocketed_coyote_F",100,"true"],
        ["vest","V_Pocketed_olive_F",100,"true"],

        /* Headgears */
        ["headgear","H_Booniehat_khk",100,"true"],
        ["headgear","H_Booniehat_oli",100,"true"],

        ["headgear","H_Hat_blue",100,"true"],
        ["headgear","H_Hat_brown",100,"true"],
        ["headgear","H_Hat_camo",100,"true"],
        ["headgear","H_Hat_checker",100,"true"],
        ["headgear","H_Hat_grey",100,"true"],
        ["headgear","H_Hat_tan",100,"true"],
        ["headgear","H_StrawHat",100,"true"],
        ["headgear","H_StrawHat_dark",100,"true"],
        ["headgear","A3PL_Fedora_Black",100,"true"],
        ["headgear","A3PL_Supreme_Fedora",1000,"true"],
        ["headgear","sl_client_c_hats_rinohat_W",100,"true"],
        ["headgear","A3PL_Rangehat",100,"true"],

        ["headgear","d3s_CAP_beanie",100,"true"],
        ["headgear","d3s_CAP_beanie1",100,"true"],
        ["headgear","d3s_CAP_beanie2",100,"true"],
        ["headgear","d3s_CAP_beanie3",100,"true"],
        ["headgear","d3s_CAP_beanie4",100,"true"],
        ["headgear","d3s_CAP_beanie5",100,"true"],
        ["headgear","d3s_CAP_beanie6",100,"true"],
        ["headgear","d3s_CAP_beanie7",100,"true"],
        ["headgear","d3s_CAP_beanie8",100,"true"],
        ["headgear","d3s_CAP_beanie_1",100,"true"],
        ["headgear","d3s_CAP_beanie_1_a",100,"true"],
        ["headgear","d3s_CAP_beanie_1_b",100,"true"],
        ["headgear","d3s_CAP_beanie_1_c",100,"true"],
        ["headgear","d3s_CAP_beanie_1_d",100,"true"],
        ["headgear","d3s_CAP_beanie_1_e",100,"true"],
        ["headgear","d3s_CAP_beanie_1_f",100,"true"],
        ["headgear","d3s_CAP_beanie_1_g",100,"true"],
        ["headgear","d3s_CAP_beanie_1_h",100,"true"],
        ["headgear","d3s_CAP_beanie_1_i",100,"true"],
        ["headgear","d3s_CAP_beanie_1_j",100,"true"],
        ["headgear","d3s_CAP_beanie_1_k",100,"true"],
        ["headgear","d3s_CAP_beanie_1_l",100,"true"],
        ["headgear","d3s_CAP_beanie_1_m",100,"true"],
        ["headgear","d3s_CAP_beanie_2_a",100,"true"],
        ["headgear","d3s_CAP_beanie_2_b",100,"true"],
        ["headgear","d3s_CAP_beanie_2_c",100,"true"],
        ["headgear","d3s_CAP_beanie_2_d",100,"true"],
        ["headgear","d3s_CAP_beanie_2_e",100,"true"],
        ["headgear","d3s_CAP_beanie_2_f",100,"true"],
        ["headgear","d3s_CAP_beanie_2_g",100,"true"],
        ["headgear","d3s_CAP_beanie_2_h",100,"true"],
        ["headgear","d3s_CAP_beanie_2_i",100,"true"],
        ["headgear","d3s_CAP_beanie_2_j",100,"true"],
        ["headgear","d3s_CAP_beanie_2_k",100,"true"],
        ["headgear","d3s_CAP_beanie_2_l",100,"true"],
        ["headgear","d3s_CAP_beanie_2_m",100,"true"],
        ["headgear","d3s_CAP_beanie_2_n",100,"true"],
        ["headgear","d3s_CAP_beanie_2_o",100,"true"],

        ["headgear","d3s_CAP_p_head_006_a",100,"true"],
        ["headgear","d3s_CAP_p_head_006_b",100,"true"],

        ["headgear","d3s_CAP_Headgear_1",100,"true"],
        ["headgear","d3s_CAP_Headgear_1_1",100,"true"],

        ["headgear","sl_client_c3_durag_black_W",100,"true"],
        ["headgear","sl_client_c3_durag_white_W",100,"true"],

        ["headgear","sl_client_c3_niggacap_back_1_W",100,"true"],
        ["headgear","sl_client_c3_durag_back_2_W",100,"true"],
        ["headgear","sl_client_c3_durag_back_1_W",100,"true"],
        ["headgear","sl_client_c3_durag_back_7_W",100,"true"],
        ["headgear","sl_client_c3_niggacap_back_3_W",100,"true"],
        ["headgear","sl_client_c3_durag_back_3_W",100,"true"],
        ["headgear","sl_client_c3_durag_back_9_W",100,"true"],
        ["headgear","sl_client_c3_durag_back_6_W",100,"true"],
        ["headgear","sl_client_c3_durag_back_12_W",100,"true"],
        ["headgear","sl_client_c3_niggacap_back_4_W",100,"true"],
        ["headgear","sl_client_c3_durag_back_4_W",100,"true"],
        ["headgear","sl_client_c3_durag_back_10_W",100,"true"],
        ["headgear","sl_client_c3_niggacap_back_5_W",100,"true"],
        ["headgear","sl_client_c3_durag_back_5_W",100,"true"],
        ["headgear","sl_client_c3_durag_back_11_W",100,"true"],
        ["headgear","sl_client_c3_niggacap_back_2_W",100,"true"],
        ["headgear","sl_client_c3_durag_back_8_W",100,"true"],
        ["headgear","sl_client_c3_niggacap_back_6_W",100,"true"],

        ["headgear","sl_client_c3_niggacap_front_1_W",100,"true"],
        ["headgear","sl_client_c3_durag_front_2_W",100,"true"],
        ["headgear","sl_client_c3_durag_front_1_W",100,"true"],
        ["headgear","sl_client_c3_durag_front_7_W",100,"true"],
        ["headgear","sl_client_c3_niggacap_front_3_W",100,"true"],
        ["headgear","sl_client_c3_durag_front_3_W",100,"true"],
        ["headgear","sl_client_c3_durag_front_9_W",100,"true"],
        ["headgear","sl_client_c3_durag_front_6_W",100,"true"],
        ["headgear","sl_client_c3_durag_front_12_W",100,"true"],
        ["headgear","sl_client_c3_niggacap_front_4_W",100,"true"],
        ["headgear","sl_client_c3_durag_front_4_W",100,"true"],
        ["headgear","sl_client_c3_durag_front_10_W",100,"true"],
        ["headgear","sl_client_c3_niggacap_front_5_W",100,"true"],
        ["headgear","sl_client_c3_durag_front_5_W",100,"true"],
        ["headgear","sl_client_c3_durag_front_11_W",100,"true"],
        ["headgear","sl_client_c3_niggacap_front_2_W",100,"true"],
        ["headgear","sl_client_c3_durag_front_8_W",100,"true"],
        ["headgear","sl_client_c3_niggacap_front_6_W",100,"true"],

        ["headgear","sl_client_c5_cap_nike_blk_W",100,"true"],
        ["headgear","sl_client_c5_cap_nike_blu_W",100,"true"],
        ["headgear","sl_client_c5_cap_nike_grn_W",100,"true"],
        ["headgear","sl_client_c5_cap_nike_grey_W",100,"true"],
        ["headgear","sl_client_c5_cap_nike_navy_W",100,"true"],
        ["headgear","sl_client_c5_cap_nike_org_W",100,"true"],
        ["headgear","sl_client_c5_cap_nike_red_W",100,"true"],
        ["headgear","sl_client_c5_cap_nike_wh_W",100,"true"],
        ["headgear","sl_client_c5_cap_nike_ylw_W",100,"true"],
        ["headgear","A3PL_Supreme_Cap",1000,"true"],
        ["headgear","A3PL_Supreme_LV",10000,"true"],
        ["headgear","A3PL_Trump_Hat",100,"true"],

        ["headgear","H_Construction_basic_black_F",100,"true"],
        ["headgear","H_Construction_basic_orange_F",100,"true"],
        ["headgear","H_Construction_basic_red_F",100,"true"],
        ["headgear","H_Construction_basic_vrana_F",100,"true"],
        ["headgear","H_Construction_basic_white_F",100,"true"],
        ["headgear","H_Construction_basic_yellow_F",100,"true"],

        ["headgear","H_Hat_Safari_olive_F",100,"true"],
        ["headgear","H_Hat_Safari_sand_F",100,"true"],

        ["headgear","sl_client_c_hats_russian_W",100,"true"],
        ["headgear","d3s_CAP_char_sniper",100,"true"],
        ["headgear","d3s_CAP_Embacy",100,"true"],
        ["headgear","d3s_CAP_furcap",100,"true"],
        ["headgear","d3s_CAP_russelite_hat",100,"true"],
        ["headgear","sl_client_c_masks_bucket_W",100,"true"],
        ["headgear","sl_client_c_masks_capital_hat_W",100,"true"],
        ["headgear","A3PL_Conehat",100,"true"],
        ["headgear","A3PL_Cowboy",100,"true"],
        ["headgear","sl_client_c_eyepatch",100,"true"],
        ["headgear","sl_client_c_masks_funnycap_W",100,"true"],
        ["headgear","sl_client_c_masks_hat_W",100,"true"],
        ["headgear","A3PL_Mexicanhat",100,"true"],
        ["headgear","sl_client_c_masks_piratehat_W",100,"true"],
        ["headgear","sl_client_c_masks_skatehelmet_W",100,"true"],
        ["headgear","sl_client_c_hats_sombrero_W",100,"true"],
        ["headgear","sl_client_c_masks_spinning_hat_W",100,"true"],
        ["headgear","sl_client_c_masks_trump_W",100,"true"],
        ["headgear","TRYK_H_LHS_HEL_G",100,"true"],
        ["headgear","TRYK_H_EARMUFF",100,"true"],
        ["headgear","sl_client_c_masks_vietnam_W",100,"true"],
        ["headgear","A3PL_WitchHat",100,"true"],

        ["headgear","d3s_CAP_berd_003_u_a",100,"true"],
        ["headgear","d3s_CAP_berd_003_u_b",100,"true"],
        ["headgear","d3s_CAP_berd_003_u_c",100,"true"],
        ["headgear","d3s_CAP_berd_003_u_d",100,"true"],
        ["headgear","d3s_CAP_berd_003_u_e",100,"true"],
        ["headgear","d3s_CAP_berd_003_u_f",100,"true"],
        ["headgear","d3s_CAP_berd_003_u_g",100,"true"],
        ["headgear","d3s_CAP_berd_003_u_h",100,"true"],
        ["headgear","d3s_CAP_berd_003_u_i",100,"true"],
        ["headgear","d3s_CAP_berd_003_u_j",100,"true"],
        ["headgear","d3s_CAP_berd_003_u_k",100,"true"],
        ["headgear","d3s_CAP_berd_003_u_l",100,"true"],
        ["headgear","d3s_CAP_berd_003_u_m",100,"true"],
        ["headgear","d3s_CAP_berd_003_u_n",100,"true"],
        ["headgear","d3s_CAP_berd_003_u_o",100,"true"],
        ["headgear","d3s_CAP_berd_003_u_p",100,"true"],
        ["headgear","d3s_CAP_berd_003_u_q",100,"true"],
        ["headgear","d3s_CAP_berd_003_u_r",100,"true"],
        ["headgear","d3s_CAP_berd_003_u_s",100,"true"],
        ["headgear","d3s_CAP_berd_003_u_t",100,"true"],
        ["headgear","d3s_CAP_berd_003_u_u",100,"true"],
        ["headgear","d3s_CAP_berd_003_u_v",100,"true"],
        ["headgear","d3s_CAP_berd_003_u_w",100,"true"],
        ["headgear","d3s_CAP_berd_003_u_x",100,"true"],
        ["headgear","d3s_CAP_berd_003_u_y",100,"true"],
        ["headgear","d3s_CAP_berd_003_u_z",100,"true"],

        ["headgear","d3s_CAP_berd_006_u_a",100,"true"],
        ["headgear","d3s_CAP_berd_006_u_b",100,"true"],
        ["headgear","d3s_CAP_berd_006_u_c",100,"true"],
        ["headgear","d3s_CAP_berd_006_u_d",100,"true"],
        ["headgear","d3s_CAP_berd_006_u_e",100,"true"],
        ["headgear","d3s_CAP_berd_006_u_f",100,"true"],
        ["headgear","d3s_CAP_berd_006_u_g",100,"true"],
        ["headgear","d3s_CAP_berd_006_u_h",100,"true"],
        ["headgear","d3s_CAP_berd_006_u_i",100,"true"],
        ["headgear","d3s_CAP_berd_006_u_j",100,"true"],
        ["headgear","d3s_CAP_berd_006_u_k",100,"true"],
        ["headgear","d3s_CAP_berd_006_u_l",100,"true"],
        ["headgear","d3s_CAP_berd_006_u_m",100,"true"],
        ["headgear","d3s_CAP_berd_006_u_n",100,"true"],

        ["headgear","d3s_CAP_Headgear",100,"true"],
        ["headgear","d3s_CAP_Headgear1",100,"true"],

        ["headgear","sl_client_c4_ninja_ShirtMask_01_W",100,"true"],
        ["headgear","sl_client_c4_ninja_ShirtMask_02_W",100,"true"],
        ["headgear","sl_client_c4_ninja_ShirtMask_03_W",100,"true"],
        ["headgear","sl_client_c4_ninja_ShirtMask_04_W",100,"true"],
        ["headgear","sl_client_c4_ninja_ShirtMask_05_W",100,"true"],
        ["headgear","sl_client_c4_ninja_ShirtMask_06_W",100,"true"],
        ["headgear","sl_client_c4_ninja_ShirtMask_07_W",100,"true"],
        ["headgear","sl_client_c4_ninja_ShirtMask_08_W",100,"true"],
        ["headgear","sl_client_c4_ninja_ShirtMask_09_W",100,"true"],
        ["headgear","sl_client_c4_ninja_ShirtMask_10_W",100,"true"],
        ["headgear","sl_client_c4_ninja_ShirtMask_11_W",100,"true"],

        ["headgear","sl_client_c_masks_anonymous_W",100,"true"],
        ["headgear","sl_client_c3_masks2_BatmanMask_W",100,"true"],
        ["headgear","sl_client_c3_masks2_GingerbreadMask_W",100,"true"],
        ["headgear","sl_client_c5_Gingerbread1_W",100,"true"],
        ["headgear","sl_client_c_masks_horse_head_W",100,"true"],
        ["headgear","sl_client_c3_masks2_JasonMask_W",100,"true"],
        ["headgear","sl_client_c3_masks2_KermitMask_W",100,"true"],
        ["headgear","sl_client_c3_knuckle",100,"true"],
        ["headgear","sl_client_c3_masque_Dallas",100,"true"],
        ["headgear","sl_client_c3_masque_Chains",100,"true"],
        ["headgear","sl_client_c3_masque_Hoxton",100,"true"],
        ["headgear","sl_client_c3_masque_Wolfv2",100,"true"],
        ["headgear","sl_client_c3_masque_Religieuse",100,"true"],
        ["headgear","sl_client_c3_masks2_MickeyMask_W",100,"true"],
        ["headgear","sl_client_c3_masks2_ShrekMask_W",100,"true"],
        ["headgear","sl_client_c3_masks2_SpidermanMask_W",100,"true"],
        ["headgear","sl_client_c3_masks2_SpongebobMask_W",100,"true"],

        /* Goggles */
        ["goggles","G_Aviator",100,"true"],
        ["goggles","G_Shades_Black",100,"true"],
        ["goggles","G_Shades_Blue",100,"true"],
        ["goggles","G_Shades_Green",100,"true"],
        ["goggles","G_Shades_Red",100,"true"],
        ["goggles","G_Spectacles",100,"true"],
        ["goggles","G_Spectacles_Tinted",100,"true"],
        ["goggles","G_Sport_Red",100,"true"],
        ["goggles","G_Sport_Blackyellow",100,"true"],
        ["goggles","G_Sport_BlackWhite",100,"true"],
        ["goggles","G_Sport_Checkered",100,"true"],
        ["goggles","G_Sport_Blackred",100,"true"],
        ["goggles","G_Sport_Greenblack",100,"true"],
        ["goggles","G_Squares",100,"true"],
        ["goggles","d3s_p_eyes_000_a",100,"true"],
        ["goggles","d3s_p_eyes_000_b",100,"true"],
        ["goggles","d3s_p_eyes_000_c",100,"true"],
        ["goggles","d3s_p_eyes_000_d",100,"true"],
        ["goggles","d3s_p_eyes_000_e",100,"true"],
        ["goggles","d3s_p_eyes_000_f",100,"true"],
        ["goggles","d3s_p_eyes_000_g",100,"true"],
        ["goggles","d3s_p_eyes_000_h",100,"true"],
        ["goggles","d3s_p_eyes_000_i",100,"true"],
        ["goggles","d3s_p_eyes_000_j",100,"true"],
        ["goggles","d3s_p_eyes_000_k",100,"true"],
        ["goggles","d3s_p_eyes_000_l",100,"true"],
        ["goggles","d3s_p_eyes_000_m",100,"true"],
        ["goggles","d3s_p_eyes_000_n",100,"true"],
        ["goggles","d3s_p_eyes_000_o",100,"true"],
        ["goggles","mgsr_eyepatch_goggles",100,"true"],
        ["goggles","G_EyeProtectors_F",100,"true"],
        ["goggles","G_Balaclava_blk",100,"true"],
        ["goggles","G_Balaclava_oli",100,"true"],
        ["goggles","G_Bandanna_blk",100,"true"],
        ["goggles","G_Bandanna_khk",100,"true"],
        ["goggles","G_Bandanna_oli",100,"true"],
        ["goggles","G_Bandanna_tan",100,"true"],
        ["goggles","G_Bandanna_aviator",100,"true"],
        ["goggles","G_Bandanna_sport",100,"true"],
        ["goggles","nigga_platok",100,"true"],
        ["goggles","nigga_platok2",100,"true"],
        ["goggles","nigga_platok3",100,"true"],
        ["goggles","nigga_platok4",100,"true"],
        ["goggles","nigga_platok5",100,"true"],
        ["goggles","nigga_platok6",100,"true"],
        ["goggles","nigga_platok7",100,"true"],
        ["goggles","nigga_platok8",100,"true"],
        ["goggles","nigga_platok9",100,"true"],
        ["goggles","nigga_platok10",100,"true"],
        ["goggles","nigga_platok11",100,"true"],
        ["goggles","nigga_platok12",100,"true"]

        /* Backpacks
        ["backpack","sl_client_c_backpack_civil01",100,"true"],
        ["backpack","sl_client_c_backpack_civil02_01",100,"true"],
        ["backpack","sl_client_c_backpack_civil02_02",100,"true"],
        ["backpack","sl_client_c_backpack_civil02_03",100,"true"],
        ["backpack","sl_client_c_backpack_civil04_01",100,"true"],
        ["backpack","sl_client_c_backpack_civil04_02",100,"true"],
        ["backpack","sl_client_c_backpack_civil04_03",100,"true"],
        ["backpack","sl_client_c_backpack_civil04_04",100,"true"],
        ["backpack","sl_client_c_backpack_civil05",100,"true"],
        ["backpack","d3s_backpack",100,"true"],
        ["backpack","d3s_backpack_a",100,"true"],
        ["backpack","d3s_backpack_b",100,"true"],
        ["backpack","d3s_backpack_c",100,"true"],
        ["backpack","d3s_backpack_d",100,"true"],
        ["backpack","d3s_backpack_e",100,"true"],
        ["backpack","d3s_backpack_f",100,"true"],
        ["backpack","d3s_backpack_g",100,"true"],
        ["backpack","d3s_backpack_h",100,"true"],
        ["backpack","d3s_backpack_i",100,"true"],
        ["backpack","d3s_backpack_j",100,"true"],
        ["backpack","d3s_backpack_k",100,"true"],
        ["backpack","d3s_backpack_l",100,"true"],
        ["backpack","d3s_backpack_m",100,"true"],
        ["backpack","A3PL_B_LegStrapBag_black_F",100,"true"],
        ["backpack","A3PL_B_LegStrapBag_coyote_F",100,"true"],
        ["backpack","A3PL_B_LegStrapBag_olive_F",100,"true"],
        ["backpack","sl_client_c_baglike_b",100,"true"],
        ["backpack","sl_client_c_baglike_bl",100,"true"],
        ["backpack","sl_client_c_baglike_gr",100,"true"],
        ["backpack","sl_client_c_baglike_pink",100,"true"],
        ["backpack","sl_client_c_baglike_pur",100,"true"],
        ["backpack","sl_client_c_baglike_r",100,"true"],
        ["backpack","sl_client_c_baglike_yel",100,"true"]
        */
    ]],
    ["Roupas SD",[
        /* Uniforms */
        ["uniform","A3PL_SD_Cadet_Test_Uniform",100,"((player getVariable ['faction_rank',0]) > 0)"],
        ["uniform","A3PL_SD_Deputy_Test_Uniform",100,"((player getVariable ['faction_rank',0]) > 1)"],
        ["uniform","A3PL_SD_SenDep_Test_Uniform",100,"((player getVariable ['faction_rank',0]) > 2)"],
        ["uniform","A3PL_SD_Sgt_Test_Uniform",100,"((player getVariable ['faction_rank',0]) > 3)"],
        ["uniform","A3PL_SD_Lt_Test_Uniform",100,"((player getVariable ['faction_rank',0]) > 4)"],
        ["uniform","A3PL_SD_Captain_Test_Uniform",100,"((player getVariable ['faction_rank',0]) > 5)"],
        ["uniform","A3PL_SD_UndSher_Test_Uniform",100,"((player getVariable ['faction_rank',0]) > 6)"],
        ["uniform","A3PL_SD_Sheriff_Test_Uniform",100,"((player getVariable ['faction_rank',0]) > 7)"],
        ["uniform","A3PL_SERT_Fatigues_Uniform",100,"(['sert'] call Caue_DMV_Check)"],
        ["uniform","A3PL_SD_ERT_Green_Test_Uniform",100,"(['sert'] call Caue_DMV_Check)"],
        ["uniform","A3PL_Detective_BlueBlue_Uniform",100,"(['dtu'] call Caue_DMV_Check)"],
        ["uniform","A3PL_Detective_White_Uniform",100,"(['dtu'] call Caue_DMV_Check)"],
        ["uniform","A3PL_Detective_Blueorange_Uniform",100,"(['dtu'] call Caue_DMV_Check)"],
        ["uniform","sl_client_c4_bigpolice_W",100,"((player getVariable ['faction_rank',0]) > 7)"],
        /* Vests */
        ["vest", "A3PL_FISD_Safety_Vest",100,"true"],
        ["vest", "A3PL_Sheriff_Rig_Test",100,"true"],
        ["vest", "A3PL_Sheriff_Test_Tac_Vest",100,"true"],
        ["vest", "A3PL_SD_Vest_Light_Test",100,"true"],
        ["vest", "A3PL_Sheriff_Belt_Test",100,"true"],
        ["vest", "A3PL_Rangemaster_belt_blk",100,"true"],
        ["vest", "A3PL_Sheriff_SERT_Vest",100,"true"],
        ["vest", "A3PL_SD_Sert_Lite",100,"true"],
        ["vest", "A3PL_SD_ERTGreen_Vest_Test",100,"true"],
        ["vest", "A3PL_Sheriff_ERT_Vest_Brwn",100,"true"],
        ["vest", "A3PL_Sheriff_K9_Vest_Brwn",100,"true"],
        ["vest", "A3PL_SD_Highway_Vest_Lite",100,"true"],
        ["vest", "A3PL_Sheriff_HWay_Vest_Brwn",100,"true"],
        ["vest", "A3PL_SD_High_Threat_Lite",100,"true"],
        ["vest", "A3PL_SD_Detective_Vest",100,"true"],
        ["vest", "A3PL_SD_Detective_Vest_Lite",100,"true"],
        ["vest", "A3PL_Sheriff_Detective_Vest_Brwn",100,"true"],
        ["vest", "A3PL_Sheriff_Wildlife_Vest_Brwn",100,"true"],
        /* Headgears */
        ["headgear","A3PL_Sheriff_Hat_lt_Brown",100,"true"],
        ["headgear","A3PL_Sheriff_Test_Hat",100,"true"],
        ["headgear","A3PL_Sheriff_Hat_Black",100,"true"],
        ["headgear","A3PL_Sheriff_Cap",100,"true"],
        ["headgear","A3PL_Sheriff_Test_Cap",100,"true"],
        ["headgear","A3PL_Sheriff_ERTGrn_Cap",100,"true"],
        ["headgear","A3PL_SERT_Helmet",100,"(['sert'] call Caue_DMV_Check)"],
        ["headgear","A3PL_SD_ERT_Green_Test_Helm",100,"(['sert'] call Caue_DMV_Check)"]
    ]],
    ["Roupas EMS",[
        /* Uniforms */
        ["uniform","Captain_uni1",100,"true"],
        ["uniform","Chief_uni1",100,"true"],
        ["uniform","Commissioner_uni1",100,"true"],
        ["uniform","DeputyChief_uni1",100,"true"],
        ["uniform","EMT_uni1",100,"true"],
        ["uniform","Lieutenant_uni1",100,"true"],
        ["uniform","paramedic_uni1",100,"true"],
        ["uniform","SEMT_uni1",100,"true"],
        ["uniform","sparamedic_uni1",100,"true"],
        ["uniform","sl_client_c_nurse_blue_W",100,"true"],
        ["uniform","sl_client_c_nurse_green_W",100,"true"],
        ["uniform","sl_client_c_nurse_white_W",100,"true"],
        ["uniform","OperationsOfficer_uni1",100,"true"],
        ["uniform","SeniorOperationsOfficer_uni1",100,"true"],
        ["uniform","SeniorTechnician_uni1",100,"true"],
        ["uniform","Technician_uni1",100,"true"],
        ["uniform","UnitCommander_uni1",100,"true"],
        ["uniform","A3PL_Air_Ambulance_Instructor_Uniform",100,"true"],
        ["uniform","A3PL_Air_Ambulance_Paramedic_Uniform",100,"true"],
        ["uniform","U_B_Wetsuit",100,"true"],
        ["uniform","A3PL_FD_Protective_Uniform",100,"true"],
        ["uniform","sl_client_c4_hazmat_yellow_W",100,"true"],
        /* Vests */
        ["vest","officer_belt",100,"true"],
        ["vest","A3PL_Air_Ambulance_Pilot_Vest",100,"true"],
        ["vest","A3PL_Air_Ambulance_Paramedic_Vest",100,"true"],
        ["vest","A3PL_FD_Oxygen",100,"true"],
        ["vest", "V_RebreatherB", 100,"true"],
        /* Headgears */
        ["headgear","A3PL_FIFR_Flight_Para_Helm",100,"true"],
        ["headgear","A3PL_FIFR_Instructor_Helm",100,"true"],
        ["headgear","A3PL_FD_Helmet",100,"true"],
        ["headgear","A3PL_FireHelmet_Captain",100,"true"],
        ["headgear","A3PL_FireHelmet_Chief",100,"true"],
        ["headgear","A3PL_FireHelmet_Engineer",100,"true"],
        ["headgear","A3PL_FireHelmet_FireFighter",100,"true"],
        ["headgear","A3PL_FireHelmet_Lieutenant",100,"true"],
        ["headgear","A3PL_FireHelmet_Probationer",100,"true"],
        /* Goggles */
        ["goggles","G_Respirator_blue_F",100,"true"],
        ["goggles","G_Respirator_white_F",100,"true"],
        ["goggles","G_Respirator_yellow_F",100,"true"],
        ["goggles", "G_Diving", 100,"true"]
    ]]
];
publicVariable "Config_Shop_Clothing";

Config_Shops_Items = [
    ["Shop_Willy", [
        ["item", "jug", 50, 0, "true"],
        ["item", "jug_moonshine", 999999, 1200, "true"]
    ], {[6960.71, 5425.69, 1]}],
    ["Shop_Hemlock", [
        ["item", "log", 999999, 75, "true"],
        ["weapon", "A3PL_FireAxe", 500, 0, "true"]
    ], {[6464.8, 5518.47, 1]}],
    ["Shop_Mike", [
        ["uniform", "A3PL_Mining_Uniform", 24, 0, "true"],
        ["headgear", "H_Construction_headset_White_F", 24, 0, "true"],
        ["weapon", "A3PL_Pickaxe", 100, 0, "true"],
        ["weapon", "A3PL_Shovel", 100, 0, "true"]
    ], {[3918.02, 6123.03, 34]}],
    ["Shop_Paintball", [
        ["magazine", "A3PL_Paintball_Mag", 25, 0, "true"],
        ["weapon", "A3PL_Paintball_Marker", 50, 0, "true"],
        ["weapon", "A3PL_Paintball_Marker_Camo", 50, 0, "true"],
        ["weapon", "A3PL_Paintball_Marker_PinkCamo", 50, 0, "true"],
        ["weapon", "A3PL_Paintball_Marker_DigitalBlue", 50, 0, "true"],
        ["weapon", "A3PL_Paintball_Marker_Green", 50, 0, "true"],
        ["weapon", "A3PL_Paintball_Marker_Purple", 50, 0, "true"],
        ["weapon", "A3PL_Paintball_Marker_Red", 50, 0, "true"],
        ["weapon", "A3PL_Paintball_Marker_Yellow", 50, 0, "true"],
        ["uniform", "A3PL_Red_Pball_Jersey_Uniform", 24, 0, "true"],
        ["uniform", "A3PL_Blue_Pball_Jersey_Uniform", 24, 0, "true"],
        ["uniform", "A3PL_Pink_Pball_Jersey_Uniform", 24, 0, "true"],
        ["uniform", "A3PL_Green_Pball_Jersey_Uniform", 24, 0, "true"],
        ["uniform", "A3PL_Purple_Pball_Jersey_Uniform", 24, 0, "true"],
        ["headgear", "A3PL_Paintball_Helmet", 50, 0]
    ], {[3541.22, 5157.83, 0.07]}],
    ["Shop_Supermarket", [
        ["item", "repairwrench", 175, 60, "true"],
        ["item", "jerrycan", 700, 250, "true"],
        ["item", "burger_full_cooked", 400, 150, "true"],
        ["item", "taco_cooked", 400, 150, "true"],
        ["item", "lamington", 600, 200, "true"],
        ["item", "sausages", 600, 200, "true"],
        ["item", "meatpie", 1600, 500, "true"],
        ["item", "coke", 100, 35, "true"]
    ], {[2597.17, 5626.85, 0.07]}],
    ["Shop_Hunting_Supplies", [
        ["weapon", "A3PL_CZ550", 1000, 0, "true"],
        ["magazine", "A3PL_5rnd_3006", 300, 0, "true"],
        ["item", "tag_meat", 30, 30, "true"],
        ["item", "meat_goat_tag", 600, 300, "true"],
        ["item", "meat_sheep_tag", 600, 300, "true"],
        ["item", "meat_boar_tag", 600, 300, "true"]
    ], {[2612.93, 5615.92, 0.08]}],
    ["Shop_General_Supplies", [
        ["aitem", "RoleplayRadio", 100, 0, "true"],
        ["aitem", "ItemCompass", 500, 0, "true"],
        ["aitem", "ItemGPS", 300, 0, "true"],
        ["aitem", "ItemMap", 50, 0, "true"],
        ["item", "FD_adapter", 350, 0, "true"],
        ["item", "FD_hose", 220, 0, "true"],
        ["item", "med_bandage", 100, 0, "true"],
        ["item", "med_icepack", 100, 0, "true"],
        ["item", "med_splint", 100, 0, "true"],
        ["item", "med_painkillers", 100, 0, "true"]
    ], {[2621.08, 5610.15, 0.08]}],
    ["Shop_Hardware", [
        ["item", "scale", 100, 0, "true"],
        ["item", "fan", 100, 0, "true"],
        ["item", "grinder", 500, 0, "true"],
        ["item", "planter", 50, 0, "true"],
        ["item", "lamp_200w", 500, 0, "true"],
        ["item", "lamp_500w", 1000, 0, "true"],
        ["item", "lamp_1000w", 1500, 0, "true"],
        ["item", "pavilion", 350, 0, "true"],
        ["item", "workbench", 125, 0, "true"]
    ], {[3456.32, 7513.2, 1]}],
    ["Shop_GemStone", [
        ["item", "diamond_tourmaline", 1e+008, 300, "true"],
        ["item", "diamond_aqua", 1e+008, 500, "true"],
        ["item", "diamond_alex", 1e+008, 700, "true"],
        ["item", "diamond_sapphire", 1e+008, 900, "true"],
        ["item", "diamond_ruby", 1e+008, 1100, "true"],
        ["item", "diamond_emerald", 1e+008, 1300, "true"],
        ["item", "diamond", 1e+008, 1500, "true"]
    ], {[7120.54, 7250.23, 0.2]}],
    ["Shop_FIFR_Supplies_Vendor", [
        ["item", "med_cast", 0, 0, "true"],
        ["item", "med_endotracheal", 0, 0, "true"],
        ["item", "med_icepack", 0, 0, "true"],
        ["item", "med_bandage", 0, 0, "true"],
        ["item", "med_kit", 0, 0, "true"],
        ["item", "med_oxygenmask", 0, 0, "true"],
        ["item", "med_splint", 0, 0, "true"],
        ["item", "med_painkillers", 0, 0, "true"],
        ["item", "med_autograft", 0, 0, "true"],
        ["item", "medS_bloodbag", 0, 0, "true"],
        ["item", "roadcones", 100, 50, "true"],
        ["item", "roadbarrier", 100, 50, "true"],
        ["item", "FD_yAdapter", 38, 20, "true"],
        ["item", "FD_Adapter", 38, 20, "true"],
        ["item", "FD_Hose", 67, 30, "true"],
        ["item", "FD_HydrantWrench", 38, 20, "true"],
        ["weapon", "A3PL_High_Pressure", 150, 100, "true"],
        ["weapon", "A3PL_Jaws", 150, 100, "true"],
        ["item", "FD_Mask", 93, 40, "true"],
        ["weapon", "A3PL_FireAxe", 100, 50, "true"],
        ["aitem", "ItemGPS", 300, 0, "true"]
    ], {ems_table modelToWorld [0,0,-0.5]}],
    ["Shop_FIFR_Supplies_Vendor2", [
        ["item", "roadcones", 100, 0, "true"],
        ["item", "FD_yAdapter", 38, 0, "true"],
        ["item", "FD_Adapter", 38, 0, "true"],
        ["item", "FD_Hose", 67, 0, "true"],
        ["item", "FD_HydrantWrench", 38, 0, "true"],
        ["weapon", "A3PL_Jaws", 150, 0, "true"],
        ["item", "FD_Mask", 93, 0, "true"],
        ["weapon", "A3PL_FireAxe", 100, 0, "true"]
    ], {ems_table modelToWorld [0,0,-0.5]}],
    ["Shop_SD_Supplies_Vendor", [
        ["weapon", "CG_BATON", 500, 0, "true"],
        ["weapon", "A3PL_Taser", 500, 0, "true"],
        ["magazine", "A3PL_TaserMag", 100, 0, "true"],
        ["weapon", "RH_g19", 500, 0, "((player getVariable ['faction_rank',0]) > 1)"],
        ["magazine", "RH_19Rnd_9x19_g18", 300, 0, "((player getVariable ['faction_rank',0]) > 1)"],
        ["weapon", "RH_M4A1_ris", 25000, 0, "((player getVariable ['faction_rank',0]) > 5)"],
        ["magazine", "30Rnd_556x45_Stanag", 500, 0, "((player getVariable ['faction_rank',0]) > 5)"],
        ["item", "handcuffs", 15, 0, "true"],
        ["item", "stinger", 15, 0, "true"],
        ["item", "roadcones", 100, 0, "true"],
        ["item", "roadbarrier", 100, 50, "true"],
        ["aitem", "ItemGPS", 300, 0, "true"],
        ["aitem", "Rangefinder", 1000, 0, "true"]
    ], {sd_table modelToWorld [0,0,0.6]}],
    ["Shop_FAA_Supplies_Vendor", [
        ["uniform", "A3PL_GlobalAirways_Captain_Uniform", 100, 0, "true"],
        ["vest", "V_Safety_blue_F", 500, 0, "true"],
        ["vest", "V_Safety_orange_F", 500, 0, "true"],
        ["vest", "V_Safety_yellow_F", 500, 0, "true"],
        ["headgear", "H_HeadSet_black_F", 200, 0, "true"],
        ["aitem", "Rangefinder", 500, 0, "true"]
    ], {faa_table modelToWorld[0, 0, -0.5]}],
    ["Shop_DOJ_Supplies_Vendor", [
        ["uniform", "KAEL_SUITS_BR_Judge", 24, 0, "true"],
        ["uniform", "A3PL_DOJ_Badge_and_Shirt_Uniform", 24, 0, "true"],
        ["uniform", "A3PL_DOJ_UnderClothes_Uniform", 24, 0, "true"],
        ["uniform", "A3PL_Nikos_Aged_Uniform", 24, 0, "true"],
        ["vest", "A3PL_DOJ_Protective_Vest", 24, 0, "true"],
        ["vest", "A3PL_DOJ_Black_VEST", 24, 0, "true"],
        ["vest", "A3PL_DOJ_Black_TacVest", 24, 0, "true"],
        ["vest", "A3PL_Rangemaster_belt_blk", 24, 0, "true"],
        ["headgear", "A3PL_DOJ_Hat", 24, 0, "true"]
    ], {doj_table modelToWorld[0, 0, -0.5]}],
    ["Shop_DMV_Supplies_Vendor", [
        ["weapon", "A3PL_Taser", 500, 0, "((player getVariable ['faction_rank',0]) > 1)"],
        ["magazine", "A3PL_TaserMag", 100, 0, "((player getVariable ['faction_rank',0]) > 1)"],
        ["weapon", "CG_TELBAT", 150, 0, "((player getVariable ['faction_rank',0]) > 1)"],
        ["item", "handcuffs", 15, 0, "true"],
        ["item", "roadcones", 100, 0, "true"],
        ["item", "roadbarrier", 100, 50, "true"],
        ["aitem", "Rangefinder", 1000, 0, "true"],
        ["headgear", "A3PL_DMV_Cap", 100, 0, "true"],
        ["uniform", "A3PL_DMV_Employee_Uniform", 200, 0, "true"],
        ["uniform", "A3PL_DMV_Supervisor_Uniform", 200, 0, "true"],
        ["uniform", "A3PL_DMV_AsstManager_Uniform", 200, 0, "((player getVariable ['faction_rank',0]) > 1)"],
        ["uniform", "A3PL_DMV_Manager_Uniform", 200, 0, "((player getVariable ['faction_rank',0]) > 2)"],
        ["vest", "A3PL_DMV_Safety_Vest", 250, 0, "true"]
    ], {doj_table modelToWorld[0, 0, -0.5]}],
    ["Shop_DOC_Supplies_Vendor", [
        ["uniform", "A3PL_Correctional_Officer_Uniform", 24, 0, "true"],
        ["uniform", "A3PL_Correctional_Director_Uniform", 24, 0, "true"],
        ["uniform", "A3PL_doc_green_Uniform", 24, 0, "true"],
        ["uniform", "A3PL_doc_blue_Uniform", 24, 0, "true"],
        ["uniform", "A3PL_doc_yellow_Uniform", 24, 0, "true"],
        ["uniform", "A3PL_doc_orange_Uniform", 24, 0, "true"],
        ["uniform", "A3PL_doc_red_Uniform", 24, 0, "true"],
        ["uniform", "A3PL_doc_pink_Uniform", 24, 0, "true"],
        ["vest", "A3PL_US_Marshall_Vest", 100, 0, "true"],
        ["vest", "A3PL_US_Marshall_Grey_Vest", 100, 0, "true"],
        ["vest", "A3PL_US_Marshall_SOG_Lite", 100, 0, "true"],
        ["vest", "A3PL_US_Marshall_Rig_Black", 100, 0, "true"],
        ["vest", "A3PL_US_Marshall_Blk_Lite", 100, 0, "true"],
        ["vest", "A3PL_US_Marshall_Rig_Tan", 100, 0, "true"],
        ["vest", "A3PL_US_Marshall_Tan_Lite", 100, 0, "true"],
        ["uniform", "A3PL_US_Marshall_Uniform", 100, 0, "true"],
        ["uniform", "A3PL_US_Marshall_Blue_BlkPants_Uniform", 100, 0, "true"],
        ["uniform", "A3PL_US_Marshall_Blue_Uniform", 100, 0, "true"],
        ["uniform", "A3PL_US_Marshall_Command_Uniform", 100, 0, "true"],
        ["uniform", "A3PL_US_Marshall_Supervisor_Uniform", 100, 0, "true"],
        ["uniform", "A3PL_Marshall_Fatigues_Uniform", 100, 0, "true"],
        ["uniform", "A3PL_Marshall_FGTF_Uniform", 100, 0, "true"],
        ["vest", "A3PL_Rangemaster_belt_blk", 24, 0, "true"],
        ["vest", "A3PL_DOC_Duty_Belt", 24, 0, "true"],
        ["vest", "A3PL_SD_LightVest_Vest", 500, 0, "true"],
        ["vest", "A3PL_DOC_Officer_Vest", 24, 0, "true"],
        ["headgear", "A3PL_US_Marshall_Cap", 50, 0, "true"],
        ["headgear", "A3PL_Marshal_SOG_Helmet", 50, 0, "true"],
        ["headgear", "A3PL_Sheriff_Hat", 500, 0, "true"],
        ["headgear", "A3PL_DOJ_Hat", 24, 0, "true"],
        ["weapon", "hgun_Rook40_F", 500, 0, "true"],
        ["magazine", "30Rnd_9x21_Mag", 300, 0, "true"],
        ["weapon", "A3PL_Taser", 500, 0, "true"],
        ["magazine", "A3PL_TaserMag", 100, 0, "true"],
        ["item", "handcuffs", 15, 0, "true"],
        ["item", "stinger", 15, 0, "true"],
        ["item", "roadcones", 100, 0, "true"]
    ], {doc_table modelToWorld[0, 0, -0.5]}],
    ["Shop_USCG_Supplies_Vendor", [
        ["uniform", "A3PL_USCG_Seaman_Recruit_Uniform", 24, 0, "true"],
        ["vest", "A3PL_USCG_Rig_Lite", 24, 0, "true"],
        ["headgear", "A3PL_USCG_Hat_Logo_Text", 50, 0, "true"],
        ["uniform", "U_B_Wetsuit", 24, 0, "true"],
        ["vest", "V_RebreatherB", 24, 0, "true"],
        ["goggles", "G_Diving", 50, 0, "true"],
        ["uniform", "A3PL_CGPilot_Green_CWO_Uniform", 24, 0, "(['pilotcop'] call Caue_DMV_Check)"],
        ["headgear", "H_PilotHelmetHeli_B", 50, 0, "(['pilotcop'] call Caue_DMV_Check)"],
        ["weapon", "A3PL_Taser", 100, 0, "true"],
        ["magazine", "A3PL_TaserMag", 100, 0, "true"],
        ["weapon", "RH_m9", 1000, 0, "((player getVariable ['faction_rank',0]) > 1)"],
        ["magazine", "RH_15Rnd_9x19_M9", 200, 0, "((player getVariable ['faction_rank',0]) > 1)"],
        ["weapon", "hlc_rifle_Colt727", 20000, 0, "((player getVariable ['faction_rank',0]) > 5)"],
        ["magazine", "30Rnd_556x45_Stanag", 1000, 0, "((player getVariable ['faction_rank',0]) > 5)"],
        ["weapon", "srifle_LRR_SOS_F", 5000, 0, "(['uscgsnipercop'] call Caue_DMV_Check)"],
        ["magazine", "7Rnd_408_Mag", 500, 0, "(['uscgsnipercop'] call Caue_DMV_Check)"],
        ["weapon", "arifle_SDAR_F", 3000, 0, "((player getVariable ['faction_rank',0]) > 5)"],
        ["magazine", "20Rnd_556x45_UW_mag", 100, 0, "((player getVariable ['faction_rank',0]) > 5)"],
        ["item", "handcuffs", 15, 0, "true"],
        ["item", "roadcones", 100, 0, "true"],
        ["item", "roadbarrier", 100, 50, "true"],
        ["aitem", "Rangefinder", 1000, 0, "true"],
        ["aitem", "ItemGPS", 300, 0, "true"],
        ["aitem", "NVGoggles_OPFOR", 2500, 0, "true"]
    ], {uscg_table modelToWorld[0, 0, -0.5]}],
    ["Shop_Seeds", [
        ["item", "seed_corn", 100, 0, "true"],
        ["item", "seed_wheat", 100, 0, "true"],
        ["item", "seed_lettuce", 100, 0, "true"],
        ["item", "seed_coca", 100, 0, "true"],
        ["item", "seed_sugar", 100, 0, "true"]
    ], {[4147.36, 5685, 0.3]}],
    ["Shop_Guns_Vendor", [
        ["weapon", "A3PL_Taser", 5000, 0, "true"],
        ["magazine", "A3PL_TaserMag", 100, 0, "true"],
        ["weapon", "RH_p226", 25000, 20000, "((player getVariable ['faction_rank',0]) > 1)"],
        ["magazine", "RH_15Rnd_9x19_SIG", 900, 500, "((player getVariable ['faction_rank',0]) > 1)"]
    ], {[6105.3, 7367.8, 0.2]}],
    ["Shop_DrugsDealer", [
        ["item", "seed_marijuana", 500, 250, "true"],
        ["item", "weed_5g", 2100, 200, "true"],
        ["item", "weed_10g", 2200, 400, "true"],
        ["item", "weed_15g", 2300, 600, "true"],
        ["item", "weed_20g", 2400, 800, "true"],
        ["item", "weed_25g", 2500, 1000, "true"],
        ["item", "weed_30g", 2600, 1200, "true"],
        ["item", "weed_35g", 2700, 1400, "true"],
        ["item", "weed_40g", 2800, 1600, "true"],
        ["item", "weed_45g", 2900, 1800, "true"],
        ["item", "weed_50g", 3000, 2000, "true"],
        ["item", "weed_55g", 3100, 2200, "true"],
        ["item", "weed_60g", 3200, 2400, "true"],
        ["item", "weed_65g", 3300, 2600, "true"],
        ["item", "weed_70g", 3400, 2800, "true"],
        ["item", "weed_75g", 3500, 3000, "true"],
        ["item", "weed_80g", 4000, 3200, "true"],
        ["item", "weed_85g", 4500, 3400, "true"],
        ["item", "weed_90g", 5000, 3600, "true"],
        ["item", "weed_95g", 5500, 3800, "true"],
        ["item", "weed_100g", 6000, 4000, "true"],
        ["item", "beer", 1000, 0, "true"],
        ["item", "beer_gold", 1000, 0, "true"],
        ["item", "cocaine", 10000, 0, "true"],
        ["item", "shrooms", 5000, 0, "true"]
    ], {DrugDealerRelative1 modelToWorld[0, 0, -0.4]}],
    ["Shop_BlackMarket", [
        ["item", "turtle", 999999, 15000, "true"],
        ["item", "seed_marijuana", 250, 100, "true"],
        ["item", "drill_bit", 7500, 3500, "true"],
        ["backpack", "A3PL_Backpack_Drill", 25000, 15000, "true"],
        ["backpack", "A3PL_Backpack_Money", 15000, 2500, "true"],
        ["item", "diamond_tourmaline_ill", 1300, 1300, "true"],
        ["item", "diamond_aqua_ill", 1500, 1500, "true"],
        ["item", "diamond_alex_ill", 1750, 1750, "true"],
        ["item", "diamond_sapphire_ill", 2000, 2000, "true"],
        ["item", "diamond_ruby_ill", 4000, 4000, "true"],
        ["item", "diamond_emerald_ill", 8000, 8000, "true"],
        ["item", "diamond_ill", 20000, 20000, "true"],
        ["item", "Blueprint_FAL", 35000, 0, "true"],
        ["item", "Blueprint_30Rnd_762x39_Mag_F", 5000, 0, "true"]
    ], {ASLToATL(Ship_BlackMarket modelToWorld[-1, 9, -4.4])}],
    ["Shop_Fisherman", [
        ["item", "net", 500, 240, "true"],
        ["item", "bucket_empty", 180, 48, "true"],
        ["item", "bucket_full", 850, 450, "true"],
        ["item", "tag_fish", 15, 0, "true"],
        ["item", "tag_shark", 200, 0, "true"],
        ["item", "mullet_tag", 999999, 75, "true"],
        ["item", "shark_2lb_tag", 999999, 1000, "true"],
        ["item", "shark_4lb_tag", 999999, 1500, "true"],
        ["item", "shark_5lb_tag", 999999, 3000, "true"],
        ["item", "shark_7lb_tag", 999999, 5000, "true"],
        ["item", "shark_10lb_tag", 999999, 10000, "true"]
    ], {[2605.13, 5621.28, 0.08]}],
    /* Furnitures */
    ["Shop_Furniture", [
        ["item", "furn_bed3", 500, 250, "true"],
        ["item", "furn_barcabinet", 500, 250, "true"],
        ["item", "furn_bookshelf", 500, 250, "true"],
        ["item", "furn_diningchair", 500, 250, "true"],
        ["item", "furn_diningtableprops", 500, 250, "true"],
        ["item", "furn_kennel", 500, 250, "true"],
        ["item", "furn_nightstand", 500, 250, "true"],
        ["item", "furn_nightstandlamp", 500, 250, "true"],
        ["item", "furn_sofa1", 500, 250, "true"],
        ["item", "furn_sofa3", 500, 250, "true"],
        ["item", "furn_cabinetdoubletop", 500, 250, "true"],
        ["item", "furn_cabinetsingletop", 500, 250, "true"],
        ["item", "furn_cabinettopcorner", 500, 250, "true"],
        ["item", "furn_countercorner", 500, 250, "true"],
        ["item", "furn_counterdoublecabinet", 500, 250, "true"],
        ["item", "furn_counterdrawer", 500, 250, "true"],
        ["item", "furn_countersinglecabinet", 500, 250, "true"],
        ["item", "furn_countertop1", 500, 250, "true"],
        ["item", "furn_countertop2", 500, 250, "true"],
        ["item", "furn_countertop3", 500, 250, "true"],
        ["item", "furn_sinkbigcounter", 500, 250, "true"],
        ["item", "furn_sinksinglecabinet", 500, 250, "true"],
        ["item", "furn_grill", 500, 250, "true"],
        ["item", "furn_chair1", 500, 250, "true"],
        ["item", "furn_chair2", 500, 250, "true"],
        ["item", "furn_chair3", 500, 250, "true"],
        ["item", "furn_chair4", 500, 250, "true"],
        ["item", "furn_bed1", 500, 250, "true"],
        ["item", "furn_bed2", 500, 250, "true"],
        ["item", "furn_cabinet1", 500, 250, "true"],
        ["item", "furn_cabinet2", 500, 250, "true"],
        ["item", "furn_cabinet3", 500, 250, "true"],
        ["item", "furn_coffeetable1", 500, 250, "true"],
        ["item", "furn_coffeetable2", 500, 250, "true"],
        ["item", "furn_coffeetable3", 500, 250, "true"],
        ["item", "furn_coffeetable4", 500, 250, "true"],
        ["item", "furn_cornersofa", 500, 250, "true"],
        ["item", "furn_dryingtowel", 500, 250, "true"],
        ["item", "furn_flasket", 500, 250, "true"],
        ["item", "furn_kitchenchair1", 500, 250, "true"],
        ["item", "furn_kitchenchair2", 500, 250, "true"],
        ["item", "furn_kitchenshelf1", 500, 250, "true"],
        ["item", "furn_kitchenshelf2", 500, 250, "true"],
        ["item", "furn_kitchenshelf3", 500, 250, "true"],
        ["item", "furn_kitchenshelfcorner", 500, 250, "true"],
        ["item", "furn_kitchentable1", 500, 250, "true"],
        ["item", "furn_kitchentable2", 500, 250, "true"],
        ["item", "furn_lamp1", 500, 250, "true"],
        ["item", "furn_lamp2", 500, 250, "true"],
        ["item", "furn_mirror", 500, 250, "true"],
        ["item", "furn_modkitchen1", 500, 250, "true"],
        ["item", "furn_modkitchen2", 500, 250, "true"],
        ["item", "furn_modkitchen3", 500, 250, "true"],
        ["item", "furn_modkitchen4", 500, 250, "true"],
        ["item", "furn_pouf", 500, 250, "true"],
        ["item", "furn_rack1", 500, 250, "true"],
        ["item", "furn_rack2", 500, 250, "true"],
        ["item", "furn_sofa4", 500, 250, "true"],
        ["item", "furn_sofa5", 500, 250, "true"],
        ["item", "furn_sofa6", 500, 250, "true"],
        ["item", "furn_sofa7", 500, 250, "true"],
        ["item", "furn_tvtable1", 500, 250, "true"],
        ["item", "furn_tvtable2", 500, 250, "true"],
        ["item", "furn_tvtable3", 500, 250, "true"]
    ], {[2466.18, 5637.45, 0]}],
    /* Vehicles */
    ["Shop_Vehicles_Supplies_Vendor", [
        /* Cars */
        ["vehicle", "A3PL_Mustang", 200000, 0, "true"],
        ["vehicle", "A3PL_BMW_M3", 65000, 0, "true"],
        ["vehicle", "A3PL_CVPI_Rusty", 16000, 0, "true"],
        ["vehicle", "A3PL_CVPI", 25000, 0, "true"],
        ["vehicle", "A3PL_Tahoe", 85000, 0, "true"],
        ["vehicle", "A3PL_Charger", 160000, 0, "true"],
        ["vehicle", "A3PL_F150", 80000, 0, "true"],
        ["vehicle", "A3PL_Ram", 31000, 0, "true"],
        ["vehicle", "A3PL_Wrangler", 31000, 0, "true"],
        ["vehicle", "A3PL_Gallardo", 420000, 0, "true"],
        ["vehicle", "A3PL_BMW_X5", 160000, 0, "true"],
        ["vehicle", "A3PL_Rover", 190000, 0, "true"],
        ["vehicle", "A3PL_Camaro", 37000, 0, "true"],
        ["vehicle", "A3PL_VetteZR1", 365000, 0, "true"],
        ["vehicle", "A3PL_CVPI_Taxi", 22000, 0, "true"],
        ["vehicle", "A3PL_MailTruck", 30000, 0, "true"],
        /* Trucks */
        ["vehicle", "A3PL_MiniExcavator", 75000, 0, "true"],
        ["vehicle", "A3PL_P362", 115000, 0, "true"],
        ["vehicle", "A3PL_P362_TowTruck", 65000, 0, "true"],
        ["vehicle", "A3PL_Boat_Trailer", 20000, 0, "true"],
        ["vehicle", "A3PL_Box_Trailer", 23000, 0, "true"],
        ["vehicle", "A3PL_Lowloader", 23000, 0, "true"],
        ["vehicle", "A3PL_Tanker_Trailer", 23000, 0, "true"],
        ["vehicle", "A3PL_Drill_Trailer", 13000, 0, "true"],
        ["vehicle", "A3PL_Small_Boat_Trailer", 13000, 0, "true"],
        /* Boats */
        ["vehicle", "A3PL_Motorboat", 7000, 0, "true"],
        ["vehicle", "A3PL_RHIB", 50000, 0, "true"]
    ], {[2942.43, 5891.42, -0.75]}],
    ["Shop_FIFR_Vehicle_Vendor", [
        /* Cars */
        ["vehicle", "A3PL_E350", 25000, 20000, "true"],
        ["vehicle", "jonzie_ambulance", 25000, 20000, "true"],
        ["vehicle", "A3PL_Tahoe_FD", 25000, 20000, "true"],
        ["vehicle", "A3PL_Tahoe_PD", 25000, 20000, "true"],
        ["vehicle", "A3PL_Charger_PD", 25000, 20000, "true"],
        /* Trucks */
        ["vehicle", "A3PL_Pierce_Ladder", 35000, 30000, "true"],
        ["vehicle", "A3PL_Pierce_Heavy_Ladder", 35000, 30000, "true"],
        ["vehicle", "A3PL_Pierce_Pumper", 35000, 30000, "true"]
    ], {[2942.43, 5891.42, -0.75]}],
    ["Shop_SD_Vehicles_Vendor", [
        /* Cars */
        ["vehicle", "A3PL_CVPI_PD", 25000, 20000, "true"],
        ["vehicle", "A3PL_CVPI_PD_Slicktop", 25000, 20000, "(['dtu'] call Caue_DMV_Check)"],
        ["vehicle", "A3PL_Tahoe_PD", 25000, 20000, "((player getVariable ['faction_rank',0]) > 1)"],
        ["vehicle", "A3PL_Tahoe_PD_Slicktop", 25000, 20000, "(['dtu'] call Caue_DMV_Check)"],
        ["vehicle", "A3PL_Mustang_PD", 35000, 30000, "((player getVariable ['faction_rank',0]) > 4)"],
        ["vehicle", "A3PL_Mustang_PD_Slicktop", 35000, 30000, "(['dtu'] call Caue_DMV_Check)"],
        ["vehicle", "A3PL_Charger_PD", 25000, 20000, "((player getVariable ['faction_rank',0]) > 3)"],
        ["vehicle", "A3PL_Charger_PD_Slicktop", 25000, 20000, "(['dtu'] call Caue_DMV_Check)"],
        ["vehicle", "A3PL_Silverado_PD", 25000, 20000, "((player getVariable ['faction_rank',0]) > 4)"],
        ["vehicle", "A3PL_VetteZR1_PD", 35000, 30000, "(['dtu'] call Caue_DMV_Check)"],
        /* Trucks */
        ["vehicle", "A3PL_P362_TowTruck", 35000, 30000, "(['highway'] call Caue_DMV_Check)"]
    ], {[2942.43, 5891.42, -0.75]}],
    ["Shop_FAA_Vehicles_Vendor", [
        /* Cars */
        ["vehicle", "A3PL_Tahoe", 16000, 0, "true"],
        ["vehicle", "A3PL_Fuel_Van", 16000, 0, "true"],
        /* Planes */
        ["vehicle", "A3PL_Goose_Base", 50000, 0, "true"],
        ["vehicle", "A3PL_Cessna172", 50000, 0, "true"],
        ["vehicle", "Heli_Medium01_Medic_H", 50000, 0, "true"],
        ["vehicle", "Heli_Medium01_Luxury_H", 50000, 0, "true"]
    ], {[2514.26, 5272.71, 1.5]}],
    ["Shop_DOJ_Vehicles_Vendor", [
        /* Cars */
        ["vehicle", "A3PL_Tahoe_PD_Slicktop", 16000, 0, "true"],
        ["vehicle", "A3PL_Tahoe", 16000, 0, "true"],
        ["vehicle", "A3PL_Charger", 25000, 20000, "true"],
        ["vehicle", "A3PL_CVPI_PD_Slicktop", 25000, 20000, "true"]
    ], {[2514.26, 5272.71, 2]}],
    ["Shop_DMV_Vehicles_Vendor", [
        /* Cars */
        ["vehicle", "A3PL_Tahoe", 16000, 0, "((player getVariable ['faction_rank',0]) > 1)"],
        ["vehicle", "A3PL_Tahoe_PD_Slicktop", 16000, 0, "((player getVariable ['faction_rank',0]) > 1)"],
        ["vehicle", "A3PL_F150_Marker", 16000, 0, "((player getVariable ['faction_rank',0]) > 1)"],
        ["vehicle", "A3PL_CRX", 16000, 0, "true"],
        /* Trucks */
        ["vehicle", "A3PL_P362_Garbage_Truck", 16000, 0, "true"]
    ], {[2514.26, 5272.71, 2]}],
    ["Shop_USCG_Car_Vendor", [
        /* Cars */
        ["vehicle", "A3PL_CVPI_PD", 25000, 20000, "true"],
        ["vehicle", "A3PL_CVPI_PD_Slicktop", 25000, 20000, "true"],
        ["vehicle", "A3PL_Charger_PD", 25000, 20000, "true"],
        ["vehicle", "A3PL_Charger_PD_Slicktop", 25000, 20000, "true"],
        ["vehicle", "A3PL_Tahoe_PD", 25000, 20000, "true"],
        ["vehicle", "A3PL_Tahoe_PD_Slicktop", 25000, 20000, "true"],
        ["vehicle", "A3PL_Silverado_PD", 25000, 20000, "true"]
    ], {[2942.43, 5891.42, -0.75]}],
    ["Shop_USCG_Boat_Vendor", [
        /* Boats */
        ["vehicle", "A3PL_RBM", 25000, 0, "true"],
        ["vehicle", "A3PL_Motorboat_Rescue", 5000, 0, "true"],
        ["vehicle", "A3PL_RHIB", 8000, 0, "true"]
    ], {[1974.44, 4935.32, 10]}],
    ["Shop_USCG_Plane_Vendor", [
        /* Planes */
        ["vehicle", "Heli_Medium01_Sheriff_H", 50000, 0, "(['pilotcop'] call Caue_DMV_Check)"],
        ["vehicle", "Heli_Medium01_Medic_H", 50000, 0, "(((player getVariable ['job','unemployed']) isEqualTo 'fifr') && ((player getVariable ['faction_rank',0]) > 5))"],
        ["vehicle", "A3PL_Jayhawk", 30000, 0, "((((player getVariable ['job','unemployed']) isEqualTo 'fifr') && ((player getVariable ['faction_rank',0]) > 5)) || (['pilotcop'] call Caue_DMV_Check))"],
        ["vehicle", "A3PL_Goose_USCG", 15000, 0, "((((player getVariable ['job','unemployed']) isEqualTo 'fifr') && ((player getVariable ['faction_rank',0]) > 5)) || (['pilotcop'] call Caue_DMV_Check))"]
    ], {[2514.26, 5272.71, 1.5]}]
];
publicVariable "Config_Shops_Items";
