/* Commons */
#include "common.hpp"
#include "macros.hpp"
#include "Caue_Common.hpp"

/* Dialogs */
#include "Dialog_Cellphone.hpp"
#include "Dialog_Shop.hpp"
#include "Dialog_PoliceDatabase.hpp"
#include "Dialog_PatDown.hpp"
#include "Dialog_NPC.hpp"
#include "Dialog_CreateTicket.hpp"
#include "Dialog_ReceiveTicket.hpp"
#include "Dialog_JailPlayer.hpp"
#include "Dialog_Admin.hpp"
#include "Dialog_Phone_Active.hpp"
#include "Dialog_Phone_UberMenu.hpp"
#include "Dialog_UberAccept.hpp"
#include "Dialog_Nametag.hpp"
#include "Dialog_Dispatch.hpp"
#include "Dialog_Kane9.hpp"
#include "Dialog_ATC.hpp"
#include "Dialog_Transponder.hpp"
#include "Dialog_Treasury.hpp"
#include "Dialog_Paintball.hpp"
#include "Dialog_Twitter.hpp"
#include "Dialog_BusinessRent.hpp"
#include "Dialog_ItemSale.hpp"
#include "Dialog_ItemBuy.hpp"
#include "Dialog_Gasstation.hpp"
#include "Dialog_Factory.hpp"
#include "Dialog_Garage.hpp"
#include "Dialog_Vote.hpp"
#include "Dialog_FactionSetup.hpp"
#include "Dialog_Prospect.hpp"
#include "Dialog_ProspectFound.hpp"
#include "Dialog_CCTV.hpp"
#include "Dialog_TaxiMeter.hpp"
#include "Dialog_IE.hpp"
#include "Dialog_DMV.hpp"
#include "Dialog_BagWeed.hpp"

#include "Caue_Loading.hpp"
#include "Caue_NewPlayer.hpp"
#include "Caue_Trunk.hpp"
#include "Caue_ATM.hpp"
#include "Caue_Storage.hpp"
#include "Caue_Inventory.hpp"
#include "Caue_Clothing.hpp"
#include "Caue_Ticket.hpp"
#include "Caue_Edit.hpp"
#include "Caue_Interaction.hpp"
#include "Caue_Medical.hpp"
#include "Caue_Animations.hpp"
#include "Caue_Debug.hpp"
#include "Caue_Wiki.hpp"
#include "Caue_Combine.hpp"

/* Titles */
class RscTitles {
	#include "Dialog_HUD.hpp"
	#include "Dialog_Hud_Overlay.hpp"
	#include "Dialog_HUD_Twitter.hpp"
	#include "Dialog_HUD_Cellphone.hpp"
	#include "Dialog_HUD_Paintball.hpp"

	#include "Caue_Progress.hpp"
	#include "Caue_IDCard.hpp"
};
