#define F(NAME,TARGET) class NAME { \
    allowedTargets = TARGET; \
};
#define JIP(NAME,TARGET) class NAME { \
    allowedTargets = TARGET; \
    jip = 1; \
};

#define ANYONE 0
#define CLIENT 1
#define SERVER 2

class CfgRemoteExec {
    class Functions {
        mode = 1;
        jip = 0;

        /* Client */
        F(A3PL_fnc_Boot_Ambulance, CLIENT)
        F(A3PL_HUD_Notification, CLIENT)
        F(A3PL_Business_BuyItemReceive, CLIENT)
        F(A3PL_Dogs_BuyReceive, CLIENT)
        F(A3PL_Government_NewLaw, CLIENT)
        F(A3PL_Government_NewTax, CLIENT)
        F(A3PL_IE_ShipLeft, CLIENT)
        F(A3PL_IE_ShipArrived, CLIENT)
        F(A3PL_JobFarming_PlantReceive, CLIENT)
        F(A3PL_JobFisherman_DeployNetResponse, CLIENT)
        F(A3PL_JobFisherman_DeployNetSuccess, CLIENT)
        F(A3PL_JobMcfisher_CookBurger, CLIENT)
        F(A3PL_JobMDelivery_addJobReceive, CLIENT)
        F(A3PL_JobMDelivery_ReceiveJobList, CLIENT)
        F(A3PL_JobOil_PumpReceive, CLIENT)
        F(A3PL_JobRoadWorker_MarkResponse, CLIENT)
        F(A3PL_NPC_TakeJobResponse, CLIENT)
        F(A3PL_Lib_MoveInPass, CLIENT)
        F(A3PL_Police_DragReceive, CLIENT)
        F(Caue_Police_AcceptDispatch, CLIENT)
        F(Caue_Police_DatabaseEnterReceive, CLIENT)
        F(A3PL_Uber_RecieveRequest, CLIENT)
        F(A3PL_Vehicle_AtegoTowResponse, CLIENT)
        F(A3PL_Vehicle_DestroyedMsg, CLIENT)

        F(Caue_FactionSetup_Members, CLIENT)
        F(Caue_Gear_NewPlayer, CLIENT)
        F(Caue_Items_RemoteRocket, CLIENT)
        F(Caue_Items_ThrowPopcorn, CLIENT)
        F(Caue_Storage_Receive, CLIENT)
        F(Caue_Police_JailLoop, CLIENT)
        F(Caue_Robbery_PatDown, CLIENT)
        F(Caue_Police_TicketReceive, CLIENT)
        F(Caue_Player_SurrenderAnim, CLIENT)
        F(Caue_Police_CuffAnim, CLIENT)
        F(Caue_Robbery_ShopPolice, CLIENT)
        F(Caue_HUD_IDCard, CLIENT)
        F(Caue_Medical_DieNotification, CLIENT)
        F(Caue_Medical_Die, CLIENT)
        F(Caue_Animations_Smoke, CLIENT)
        F(Caue_BHeist_Alert, CLIENT)
        F(Caue_Phone_CallAccepted, CLIENT)
        F(Caue_Phone_CallEnded, CLIENT)
        F(Caue_Phone_RecieveMessage, CLIENT)
        F(Caue_Phone_IncomingCall, CLIENT)
        F(Caue_Government_Notification, CLIENT)
        F(Caue_Twitter_NewMsg, CLIENT)

        /* Server */
        F(Server_Setup_SetupFiles, SERVER)
        F(Server_Vehicle_TrailerDetach, SERVER)
        F(Server_Vehicle_AtegoHandle, SERVER)
        F(A3PL_Lib_SyncAnim, ANYONE)
        F(Server_Housing_LoadBox, SERVER)
        F(Server_Housing_SaveBox, SERVER)
        F(A3PL_USCG_WaterCannon, ANYONE)
        F(Server_Core_ChangeVar, SERVER)
        F(Server_Housing_InitLottery, SERVER)
        F(Caue_Log_Admin, SERVER)
        F(Server_Factory_Add, SERVER)
        F(Server_Mayor_StartVote, SERVER)
        F(Server_IE_ShipImport, SERVER)
        F(Server_Factory_Create, SERVER)
        F(Caue_Log_Misc, SERVER)
        F(Server_Vehicle_Spawn, SERVER)
        F(A3PL_Lib_HideObject, SERVER)
        F(Server_Business_BuyItem, SERVER)
        F(Server_Business_Buy, SERVER)
        F(Server_Business_Sellitem, SERVER)
        F(Server_Business_Sellitemstop, SERVER)

        F(Server_Dogs_HandleLocality, SERVER)
        F(Server_Dogs_BuyRequest, SERVER)
        F(Server_Police_Impound, SERVER)
        F(Server_Factory_Collect, SERVER)
        F(Server_Factory_Finalise, SERVER)
        F(Server_Inventory_Drop, SERVER)
        F(A3PL_Lib_ChangeLocality, SERVER)
        F(Server_Fire_RemoveFires, SERVER)
        F(Server_Fire_StartFire, SERVER)
        F(Server_Government_AddBalance, SERVER)
        F(Server_Mayor_AddCandidate, SERVER)
        F(Server_Government_ChangeLaw, SERVER)
        F(Server_Government_AddRank, SERVER)
        F(Server_Government_FactionSetupInfo, SERVER)
        F(Server_Government_RemoveRank, SERVER)
        F(Server_Government_SetPay, SERVER)
        F(Server_Government_SetRank, SERVER)
        F(Server_Government_SetTax, SERVER)
        F(Server_Mayor_AddVote, SERVER)
        F(Server_Housing_AssignHouse, SERVER)
        F(Server_Housing_LoadItemsSimulation, SERVER)
        F(Server_Inventory_Change, SERVER)
        F(Server_Housing_dropKey, SERVER)
        F(Server_Housing_CreateKey, SERVER)
        F(Server_JobFarming_Plant, SERVER)
        F(Server_JobFarming_Harvest, SERVER)
        F(Server_JobFisherman_DeployNet, SERVER)
        F(Server_JobFisherman_GrabNet, SERVER)
        F(Server_JobMcfisher_combine, SERVER)
        F(Server_JobMcfisher_cookthres, SERVER)
        F(Server_JobMDelivery_Collect, SERVER)
        F(Server_JobMDelivery_Deliver, SERVER)
        F(Server_JobMDelivery_SendJobList, SERVER)
        F(Server_JobMDelivery_Take, SERVER)
        F(Server_JobOil_PumpStart, SERVER)
        F(Server_JobRoadWorker_Impound, SERVER)
        F(Server_JobRoadWorker_UnMark, SERVER)
        F(Server_JobRoadWorker_Mark, SERVER)
        F(Server_JobWildCat_SpawnRes, SERVER)
        F(Server_Gear_Load, SERVER)
        F(Server_NPC_RequestJob, SERVER)
        F(Server_Police_EndDispatch, SERVER)
        F(Server_Police_CallDispatch, SERVER)
        F(Server_Player_TransferBank, SERVER)
        F(Server_Player_BLVariablesSetup, SERVER)
        F(Server_GetTimeTillRestart, SERVER)
        F(Server_Gear_NewRecieve, SERVER)
        F(Server_Police_Database, SERVER)
        F(Server_Police_AcceptDispatch, SERVER)
        F(Server_Vehicle_EnableSimulation, SERVER)
        F(Server_Vehicle_Sell, SERVER)
        F(Server_Lumber_TreeRespawn, SERVER)
        F(Caue_Log_Chat, SERVER)
        F(Server_Uber_addDriver, SERVER)
        F(Server_Uber_removeDriver, SERVER)
        F(Server_Uber_requestDriver, SERVER)
        F(Server_Vehicle_Trailer_Hitch, SERVER)
        F(Server_Gear_Save, SERVER)
        F(Server_FactionVehicles_Update, SERVER)
        F(Server_FactionVehicles_Create, SERVER)
        F(Server_Government_Balance, SERVER)
        F(Server_Government_Tax, SERVER)
        F(AFPL_Server_Gov_Update_Law, SERVER)
        F(AFPL_Server_Gov_Add_Law, SERVER)
        F(AFPL_Server_Gov_Remove_Law, SERVER)
        F(Server_Government_ReceiveTax, SERVER)
        F(Server_Government_UpdateBalance, SERVER)
        F(Server_FactionSetup_SetRankPay, SERVER)
        F(Server_FactionSetup_ChangeRank, SERVER)
        F(Server_Housing_RemoveHouse, SERVER)
        F(Server_Vehicle_Buy, SERVER)
        F(Server_FactionSetup_Members, SERVER)
        F(Server_FactionSetup_AddToFaction, SERVER)

        F(CAUE_Vehicle_SaveColor, SERVER)

        F(Caue_Log_Anticheat, SERVER)
        F(Caue_Log_Shop, SERVER)
        F(Server_Storage_Retrieve, SERVER)
        F(Server_Storage_Store, SERVER)
        F(Server_Storage_StorePos, SERVER)
        F(Server_Storage_ReturnVehicles, SERVER)
        F(Server_Police_TicketPay, SERVER)
        F(Server_Inventory_Pickup, SERVER)
        F(Server_Garage_Tuning, SERVER)
        F(Server_DMV_Change, SERVER)
        F(Caue_Debug_ExecRequest, SERVER)
        F(Caue_Log_Factory, SERVER)
        F(Caue_Log_Debug, SERVER)

        /* Anyone */
        F(CAUE_Hydrogen_Fuel, ANYONE)
    };

    class Commands {
        mode = 1;
        jip = 0;

		F(setFuel, ANYONE)
        F(setOwner, ANYONE)
        F(say3D, ANYONE)
    };
};
